ifndef::leveloffset[]
:toc: left
:toclevels: 3
:icons: font
:stem: latexmath
endif::[]

ifndef::imagesdir[]
:imagesdir: images
endif::[]

include::header.adoc[]

include::../../attrs.adoc[]

== Strict Margin Lemma

パーセプトロンの収束定理の補題の証明を示す。

パターン集合を次のように定義する。latexmath:[Y_0, Y_1]は有限集合で、latexmath:[Y_0 \cup Y_1 = Y]である。
さらに、latexmath:[Y_1]は正例の集合、latexmath:[Y_0]は負例の集合であるとする。
[stem,latexmath]
++++
\begin{aligned}
\forall y \in Y_1: v^t y = v_0 + v_1 y_1 + \cdots + v_n y_n \ge 0 \\
\forall y \in Y_0: v^t y = v_0 + v_1 y_1 + \cdots + v_n y_n \lt 0
\end{aligned}
++++

Lemma 1. ある正定数 latexmath:[a > 0]が存在して、すべての latexmath:[y \in Y]に対して、次の不等式が成り立つ。
[stem,latexmath]
++++
\begin{aligned}
\forall y \in Y_1: v^t y \gt +a \\
\forall y \in Y_0: v^t y \lt -a
\end{aligned}
++++

=== 証明
次のように、パーセプトロンの標準的な設定では、latexmath:[Y_0]とlatexmath:[Y_1]は有限集合であり、最小値と最大値が存在する。
[stem,latexmath]
++++
\begin{aligned}
\hat{y}_1 = \arg\min_{y \in Y_1} w^t y \\
\hat{y}_0 = \arg\max_{y \in Y_0} w^t y
\end{aligned}
++++

パターン集合が線形分離可能であることから、latexmath:[w^t \hat{y}_0 \lt w^t \hat{y}_1]を満たす 重みベクトルlatexmath:[w]が存在する。
latexmath:[w^t \hat{y}_0 \lt k \lt w^t \hat{y}_1]を満たす実数latexmath:[k]が存在する。このような latexmath:[k] を考えるのはこの補題を定めたテキストの問題設定に欠陥があるからである。
具体的には、latexmath:[y, v] が latexmath:[\forall y \in Y_1: v^t y = v_0 + v_1 y_1 + \cdots + v_n y_n = 0]の時も線形分離の条件を満たすが、一方で latexmath:[a > 0]を満たすようなマージンが存在しない。しかし、latexmath:[v_0]の選び方により、latexmath:[\forall y \in Y_1: v^t y = v_0 + v_1 y_1 + \cdots + v_n y_n \gt 0]となるようなlatexmath:[v_0]を選ぶこともできる。
そのため、 latexmath:[\forall y \in Y_1: v^t y = v_0 + v_1 y_1 + \cdots + v_n y_n \gt 0]と問題設定を変えても、便宜上 latexmath:[k]を設定したとしても、結論には影響はない。具体的な latexmath:[k] は、以下のように定めることができ、最終的にマージンlatexmath:[a]はlatexmath:[k]を使わずに表現できる。
[stem,latexmath]
++++
\begin{aligned}
k
&= \hat{y}_0 + \frac{\hat{y}_1 - \hat{y}_0}{2} \\
&= \frac{\hat{y}_1 + \hat{y}_0}{2} \\
\end{aligned}
++++

上記を満たす latexmath:[w]について、次のように定める。
[stem,latexmath]
++++
\begin{cases}
w_{+} &= w + 2a(1, \cdots, 1)^t \\
a &= \frac{k - w^t\hat{y}_0}{4(m+1)} \\
\end{cases}
++++

この後計算で使用するが、latexmath:[a]を式変形すると次のようになる。
[stem,latexmath]
++++
\begin{aligned}
a &= \frac{k - w^t\hat{y}_0}{4(m+1)} \\
4(m+1)a &= k - w^t\hat{y}_0 \\
w^t\hat{y}_0 &= k - 4(m+1)a
\end{aligned}
++++

latexmath:[y \in Y_1]のとき、次のようにマージン latexmath:[a]より大きいことが示される。
[stem,latexmath]
++++
\begin{aligned}
w_{+}^t y
&= (w + 2a(1, \cdots, 1)^t)^t y \\
&= w^t y + 2a(y_0 + y_1 + \cdots + y_m) \ge w^t y + 2a \gt w^t y + a \gt k + a \\ 
\end{aligned}
++++

latexmath:[y \in Y_0]のとき、次のようにマージン latexmath:[-a]より小さいことが示される。
[stem,latexmath]
++++
\begin{aligned}
w_{+}^t y
&= (w + 2a(1, \cdots, 1)^t)^t y \\
&= w^t y + 2a(y_0 + y_1 + \cdots + y_m) \\
&\le w^t y + 2a(m + 1) \le w^t\hat{y}_0 + 2a(m + 1) = k - 4(m+1)a + 2a(m + 1) = k - 2(m + 1)a \lt k - a
\end{aligned}
++++

以上より、次のようなlatexmath:[a]において、パターン集合が線形分離可能である前提より、補題を満たす。
[stem,latexmath]
++++
\begin{aligned}
a
&= \frac{k - w^t\hat{y}_0}{4(m+1)} \\
&= \frac{\left(w^t\hat{y}_0 + \frac{w^t\hat{y}_1 - w^t\hat{y}_0}{2}\right) - w^t\hat{y}_0}{4(m+1)} \\
&= \frac{\frac{w^t\hat{y}_1 - w^t\hat{y}_0}{2}}{4(m+1)} \\
&= \frac{w^t\hat{y}_1 - w^t\hat{y}_0}{8(m+1)} \\
\end{aligned}
++++

これで補題は証明された。
□
