ifndef::leveloffset[]
:toc: left
:toclevels: 3
:icons: font
:stem: latexmath
endif::[]

include::header.adoc[]

include::../../attrs.adoc[]

== 数学セミナー 2025年4月号

=== エレガントな回答もとむ: 1
次の連立方程式を解いてください。

[stem,latexmath]
++++
\begin{cases}
\frac{2x}{1 - x^2} = y \\
\frac{2y}{1 - y^2} = z \\
\frac{2z}{1 - z^2} = w \\
\frac{2w}{1 - w^2} = x \\
\end{cases}
++++

=== Notes 1: {f}{nbsp}^4^ = {e} の解

{f}{nbsp}^4^ = {e} ということであるから、{f}={f}を満たす場合も解に含まれる。 +
以下を計算をすると、 ({x},{nbsp}{y},{nbsp}{z},{nbsp}{w})={ (0, 0, 0, 0), (±{i}, ±{i}, ±{i}, ±{i}) }も解であると分かる。

[stem,latexmath]
++++
\begin{align*}
\frac{2x}{1-x^2} &= x \\
2x &= x (1 - x^2) \\
0 &= x (-1 - x^2) \\
0 &= x (1 + x^2) \\
\end{align*}
++++

=== Notes 2: {f}{nbsp}^2^ = {e} の解

{f}{nbsp}^4^ = {e} ということであるから、{f}={f}{nbsp}^2^ を満たす場合も解に含まれる。 +
以下を計算をすると、 ({x},{nbsp}{y},{nbsp}{z},{nbsp}{w})=(±√3, ∓√3, ±√3, ∓√3) も解であると分かる。

[stem,latexmath]
++++
\begin{align*}
\frac{2y}{1 - y^2} &= z \\ 
2y &= z (1 - y^2) \\
2y &= z (2 - (1 + y^2)) \\
\frac{y}{z} &= 1 - \frac{1 + y^2}{2} \\
\end{align*}
++++

ここで、 1 + y^2^ を計算しておく。

[stem,latexmath]
++++
\begin{align*}
1 + y^2 &= 1 + (\frac{2x}{1 - x^2})^2 \\
&= \frac{(1 - x^2)^2  + 4 x^2}{(1 - x^2)^2} \\
&= \frac{\left\{2 - (1 + x^2)\right\}^2  + 4\left\{(-1) + (1 + x^2) \right\}}{(1 - x^2)^2} \\
&= \frac{(1 + x^2)^2  -4(1 + x^2) + 4 + 4(1 + x^2) - 4}{(1 - x^2)^2} \\
&= \frac{(1 + x^2)^2}{(1 - x^2)^2} \\
&= \frac{(1 + x^2)\left\{4 + (-3 + x^2)\right\}}{(1 - x^2)^2} \\
&= \frac{(1 + x^2)(x^2 - 3) + 4(1 + x^2)}{(1 - x^2)^2} \\
\end{align*}
++++

上記を代入し、{y}を消去する。

[stem,latexmath]
++++
\begin{align*}
\frac{y}{z} &= 1 - \frac{1 + y^2}{2} \\
\frac{2x}{z(1 - x^2)}&= 1 - \frac{(1 + x^2)(x^2 - 3) + 4(1 + x^2)}{2(1 - x^2)^2} \\
\frac{4x(1 - x^2)}{z}&= 2(1 - x^2)^2 - (1 + x^2)(x^2 - 3) - 4(1 + x^2) \\
0 &= 2(1 - x^2)^2 - \frac{4x(1 - x^2)}{z} - (1 + x^2)(x^2 - 3) - 4(1 + x^2) \\
&= 2(1 - x^2)\left\{(1 - x^2) - \frac{2x}{z} \right\} - (1 + x^2)(x^2 - 3) - 4(1 + x^2) \\
&= 2\left\{2 - (1 + x^2)\right\}\left\{(1 - x^2) - 2\frac{x}{z} \right\} - (1 + x^2)(x^2 - 3) - 4(1 + x^2) \\
&= 4\left\{(1 - x^2) - \frac{2x}{z} \right\} -2(1 + x^2)\left\{(1 - x^2) - 2\frac{x}{z} \right\} - (1 + x^2)(x^2 - 3) - 4(1 + x^2) \\
&= 4\left\{2 - (1 + x^2)\right\} - 8\frac{x}{z} -2(1 + x^2)\left\{(1 - x^2) - 2\frac{x}{z} \right\} - (1 + x^2)(x^2 - 3) - 4(1 + x^2) \\
&=  8 - 4(1 + x^2) -2(1 + x^2)\left\{(1 - x^2) - 2\frac{x}{z} \right\} - (1 + x^2)(x^2 - 3) - 4(1 + x^2) - 8\frac{x}{z} \\
&= (1 + x^2)\left\lbrack -4 -2\left\{(1 - x^2) - 2\frac{x}{z}\right\} - (x^2 - 3) -4 \right\rbrack + 8 - 8\frac{x}{z} \\
&= (1 + x^2)\left\lbrack -2\left\{(-2) - (x^2 - 3)\right\} - (x^2 - 3) -8 + 4\frac{x}{z}\right\rbrack + 8 - 8\frac{x}{z} \\
&= (1 + x^2)\left\{ 2(x^2 - 3) - (x^2 - 3) + 4 -8 + 4\frac{x}{z}\right\} + 8 - 8\frac{x}{z} \\
&= (1 + x^2)\left\{ (x^2 - 3) - 4 + 4\frac{x}{z}\right\} + 8 - 8\frac{x}{z} \\
\end{align*}
++++

ここで、{z}={x}とおくと、次のようになる。

[stem,latexmath]
++++
\begin{align*}
0 &= (1 + x^2)\left\{ (x^2 - 3) - 4 + 4\frac{x}{z}\right\} + 8 - 8\frac{x}{z} \\
&= (1 + x^2)\left\{ (x^2 - 3) - 4 + 4\frac{x}{x}\right\} + 8 - 8\frac{x}{x} \\
&= (1 + x^2)(x^2 - 3) \\
\end{align*}
++++


=== Notes 3: {f}{nbsp}^2^{f}{nbsp}^2^ = {e}の解

かきかけ。
逆元が分かればやりようがあるが…。

=== Notes 4: {f}{nbsp}^4^ = {e}の解

かきかけ。
以下の式より、対称性を考慮して、同様の式を導出する。

[stem,latexmath]
++++
\begin{cases}
\frac{2z}{1 - z^2} = w \\
\frac{2w}{1 - w^2} = x \\
\end{cases}
++++

[stem,latexmath]
++++
\begin{align*}
\frac{2w}{1 - w^2} &= x \\ 
2w &= x (1 - w^2) \\
2w &= x (2 - (1 + w^2)) \\
\frac{w}{x} &= 1 - \frac{1 + w^2}{2} \\
\end{align*}
++++

同様に 1 + w^2^ を計算しておく。

[stem,latexmath]
++++
\begin{align*}
1 + w^2 &= 1 + (\frac{2z}{1 - z^2})^2 \\
&= \frac{(1 - z^2)^2  + 4 z^2}{(1 - z^2)^2} \\
&= \frac{\left\{2 - (1 + z^2)\right\}^2  + 4\left\{(-1) + (1 + z^2) \right\}}{(1 - z^2)^2} \\
&= \frac{(1 + z^2)^2  -4(1 + z^2) + 4 + 4(1 + z^2) - 4}{(1 - z^2)^2} \\
&= \frac{(1 + z^2)^2}{(1 - z^2)^2} \\
&= \frac{(1 + z^2)\left\{4 + (-3 + z^2)\right\}}{(1 - z^2)^2} \\
&= \frac{(1 + z^2)(z^2 - 3) + 4(1 + z^2)}{(1 - z^2)^2} \\
\end{align*}
++++

[stem,latexmath]
++++
\begin{align*}
\frac{w}{x} &= 1 - \frac{1 + w^2}{2} \\
\frac{2z}{x(1 - z^2)} &= 1 - \frac{(1 + z^2)(z^2 - 3) + 4(1 + z^2)}{2(1 - z^2)^2} \\
\frac{4z(1 - z^2)}{x}&= 2(1 - z^2)^2 - (1 + z^2)(z^2 - 3) - 4(1 + z^2) \\
0 &= 2(1 - z^2)^2 - \frac{4z(1 - z^2)}{x} - (1 + z^2)(z^2 - 3) - 4(1 + z^2) \\
&= 2(1 - z^2)\left\{(1 - z^2) - 2\frac{z}{x} \right\} - (1 + z^2)(z^2 - 3) - 4(1 + z^2) \\
&= 2\left\{2 - (1 + z^2)\right\}\left\{(1 - z^2) - 2\frac{z}{x} \right\} - (1 + z^2)(z^2 - 3) - 4(1 + z^2) \\
&= 4\left\{(1 - z^2) - \frac{2z}{x} \right\} -2(1 + z^2)\left\{(1 - z^2) - 2\frac{z}{x} \right\} - (1 + z^2)(z^2 - 3) - 4(1 + z^2) \\
&= 4\left\{2 - (1 + z^2)\right\} - 8\frac{z}{x} -2(1 + z^2)\left\{(1 - z^2) - \frac{2z}{x} \right\} - (1 + z^2)(z^2 - 3) - 4(1 + z^2) \\
&=  8 - 4(1 + z^2) -2(1 + z^2)\left\{(1 - z^2) - \frac{2z}{x} \right\} - (1 + z^2)(z^2 - 3) - 4(1 + z^2) - 8\frac{z}{x} \\
&= (1 + z^2)\left\lbrack -4 -2\left\{(1 - z^2) - \frac{2z}{x}\right\} - (z^2 - 3) -4 \right\rbrack + 8 - 8\frac{z}{x} \\
&= (1 + z^2)\left\lbrack -2\left\{(-2) - (z^2 - 3)\right\} - (z^2 - 3) -8 + 4\frac{z}{x}\right\rbrack + 8 - 8\frac{z}{x} \\
&= (1 + z^2)\left\{ 2(z^2 - 3) - (z^2 - 3) + 4 -8 + 4\frac{z}{x}\right\} + 8 - 8\frac{z}{x} \\
&= (1 + z^2)\left\{ (z^2 - 3) - 4 + 4\frac{z}{x}\right\} + 8 - 8\frac{z}{x} \\
&= (1 + z^2)\left\{(1 + z^2) - 8 + 4\frac{z}{x}\right\} + 8 - 8\frac{z}{x} \\
&= (1 + z^2)\left\{(1 + z^2) - 4(1 - \frac{z}{x}) - 4\right\} + 8(1 - \frac{z}{x}) \\
&= (1 + z^2)\left\{(1 + z^2) - 4\right\} - 4(1 + z^2)(1 - \frac{z}{x}) + 8(1 - \frac{z}{x}) \\
&= (1 + z^2)(z^2 - 3) + 4\left(1 - \frac{z}{x}\right)\left\{-(1 + z^2) + 2\right\} \\
\end{align*}
++++

zを消去するため、zとx式を作る。

[stem,latexmath]
++++
\begin{align*}
z &= \frac{2y}{1 - y^2} \\
&= \frac{2\cdot\frac{2x}{1 - x^2}}{1 - \left(\frac{2x}{1 - x^2}\right)^2} \\
&= 4\frac{x(1 - x^2)}{(1 - x^2)^2 - 4 x^2} \\
&= 4\frac{x(1 - x^2)}{ x^4 - 6 x^2 + 1} \\
\frac{z}{x} &= 4\frac{1 - x^2}{(1 - x^2)^2 - 4 x^2} \\
\frac{z}{x} &= 4\frac{1 - x^2}{x^4 - 6x^2 + 1} \\
1 - \frac{z}{x} &= 1 - 4\frac{1 - x^2}{x^4 - 6x^2 + 1} \\
1 - \frac{z}{x} &= \frac{(x^4 - 6x^2 + 1) - 4 + 4 x^2}{x^4 - 6x^2 + 1} \\
1 - \frac{z}{x} &= \frac{x^4 - 2x^2 - 3}{x^4 - 6x^2 + 1} \\
1 - \frac{z}{x} &= \frac{(1 + x^2)(x^2 - 3)}{x^4 - 6x^2 + 1} \\
\end{align*}
++++

(1-x^2^)^2^ - 4x^2^を計算しておく。

[stem,latexmath]
++++
\begin{align*}
(1 - x^2)^2 - 4x^2
&= x^4 - 2x^2 + 1 - 4x^2 \\
&= x^4 - 3x^2 - 3x^2 + 1 \\
&= x^2(x^2 - 3) - 3x^2 + 1 \\
&= \left\{(-1) + (1 + x^2)\right\}(x^2 - 3) - 3x^2 + 1 \\
&= (1 + x^2)(x^2 - 3) - (x^2 - 3) - 3x^2 + 1 \\
&= (1 + x^2)(x^2 - 3) - 4x^2 + 4 \\
&= (1 + x^2)(x^2 - 3) - 4(1 + x^2) + 8 \\
\end{align*}
++++

zを消去するため、 1+{z}^2^ とxの式を作る。
// 1 + z^2 &= 1 + \left\lbrack 4\frac{x(1 - x^2)}{(1 - x^2)^2 - 4 x^2} \right\rbrack^2

[stem,latexmath]
++++
\begin{align*}
1 + z^2 &= 1 + \left\{4\frac{x(1 - x^2)}{(x^4 - 6x^2 + 1)^2}\right\}^2 \\
&=\frac{(x^4 - 6x^2 + 1)^2 + 4^2 x^2 (1 - x^2)^2}{(x^4 - 6x^2 + 1)^2} \\
&=\frac{x^8 + 4x^6 + 6x^4 + 4x^2 + 1}{(x^4 - 6x^2 + 1)^2} \\
&=\frac{x^8 + x^6  + 3x^6 + 3x^4 + 3x^4 + 3x^2 + x^2 + 1}{(x^4 - 6x^2 + 1)^2} \\
&=\frac{x^6(1 + x^2)  + 3x^4(1 + x^2) + 3x^2(1 + x^2) + (1 + x^2)}{(x^4 - 6x^2 + 1)^2} \\
&=\frac{(1 + x^2)(x^6 + 3x^4 + 3x^2 + 1)}{(x^4 - 6x^2 + 1)^2} \\
&=\frac{(1 + x^2)\left\{x^4(1 + x^2) + 2x^2(1 + x^2) + (1 + x^2)\right\}}{(x^4 - 6x^2 + 1)^2} \\
&=\frac{(1 + x^2)^2(x^4 + 2x^2 + 1)}{(x^4 - 6x^2 + 1)^2} \\
&=\frac{(1 + x^2)^4}{(x^4 - 6x^2 + 1)^2} \\
\end{align*}
++++

zを消去するため、 {z}^2^ - 3 とxの式を作る。

[stem,latexmath]
++++
\begin{align*}
z^2 - 3 &= \left\{4\frac{x(1 - x^2)}{(x^4 - 6x^2 + 1)^2}\right\}^2 - 3 \\
&= \frac{4^2 x^2(1 - x^2)^2 - 3(x^4 - 6x^2 + 1)^2}{(x^4 - 6x^2 + 1)^2} \\
&= \frac{-3 x^8 + 52 x^6 -146 x^4 + 52 x^2 - 3}{(x^4 - 6x^2 + 1)^2} \\
&= \frac{(-3 x^8 + 9 x^6) + (43x^6 -129 x^4) + (- 17x^4 + 51 x^2)  + (x^2 - 3)}{(x^4 - 6x^2 + 1)^2} \\
&= \frac{-3 x^6(x^2 - 3) + 43 x^4(x^2 - 3) - 17x^2(x^2 - 3)  + (x^2 - 3)}{(x^4 - 6x^2 + 1)^2} \\
&= \frac{(x^2 - 3)(-3 x^6 + 43 x^4 - 17x^2  + 1)}{(x^4 - 6x^2 + 1)^2} \\
&= \frac{(x^2 - 3)\left\{(-3 x^6 + x^4) + (42 x^4 - 14x^2) + (- 3x^2 + 1)\right\}}{(x^4 - 6x^2 + 1)^2} \\
&= \frac{(x^2 - 3)\left\{- x^4(3x^2 - 1) + 14 x^2(3x^2 - 1) - (3x^2 - 1)\right\}}{(x^4 - 6x^2 + 1)^2} \\
&= \frac{(x^2 - 3)(3x^2 - 1)(- x^4 + 14 x^2 - 1)}{(x^4 - 6x^2 + 1)^2} \\
&= -\frac{(x^2 - 3)(3x^2 - 1)(x^4 - 14 x^2 + 1)}{(x^4 - 6x^2 + 1)^2} \\
&= -\frac{(x^2 - 3)(3x^2 - 1)\left\{(x^4 + 2x^2 + 1) - 16 x^2\right\}}{(x^4 - 6x^2 + 1)^2} \\
&= -\frac{(x^2 - 3)(3x^2 - 1)\left\{(x^2 + 1)^2 - 16 x^2\right\}}{(x^4 - 6x^2 + 1)^2} \\
&= -\frac{(x^2 - 3)(3x^2 - 1)(x^2 - 4x + 1)(x^2 + 4x + 1)}{(x^4 - 6x^2 + 1)^2} \\
\end{align*}
++++

zを消去する。
9{x}^12^ - 118 {x}^10^ + 923{x}^8^ - 2052{x}^6^ + 815 {x}^4^ - 166 {x}^2^ + 13 = 0 は、グラフでは4つの解をもつようだが、代数的に解くのは難しそうである。
解の近似値は、 ±1.614, ±0.386 となる。

[stem,latexmath]
++++
\begin{align*}
0
&= (1 + z^2)(z^2 - 3) + 4\left(1 - \frac{z}{x}\right)\left\{-(1 + z^2) + 2\right\} \\
&= \frac{(1 + x^2)^4}{(x^4 - 6x^2 + 1)^2} \cdot -\frac{(x^2 - 3)(3x^2 - 1)(x^2 - 4x + 1)(x^2 + 4x + 1)}{(x^4 - 6x^2 + 1)^2}
+ 4 \frac{(1 + x^2)(x^2 - 3)}{x^4 - 6x^2 + 1} \cdot \left\{-\frac{(1 + x^2)^4}{(x^4 - 6x^2 + 1)^2} + 2\right\} \\
&= \frac{(1 + x^2)(x^2 - 3)}{(x^4 - 6x^2 + 1)^3} \cdot -\frac{(1 + x^2)^3(3x^2 - 1)(x^2 - 4x + 1)(x^2 + 4x + 1)}{x^4 - 6x^2 + 1}
+ 4 \frac{(1 + x^2)(x^2 - 3)}{x^4 - 6x^2 + 1} \cdot \frac{-(1 + x^2)^4 + 2 (x^4 - 6x^2 + 1)^2}{(x^4 - 6x^2 + 1)^2} \\
&= \frac{(1 + x^2)(x^2 - 3)}{(x^4 - 6x^2 + 1)^3} \cdot 
\left\{
-\frac{(1 + x^2)^3(3x^2 - 1)(x^2 - 4x + 1)(x^2 + 4x + 1)}{x^4 - 6x^2 + 1}
-4(1 + x^2)^4 + 8 (x^4 - 6x^2 + 1)^2
\right\} \\
&= \frac{(1 + x^2)(x^2 - 3)}{(x^4 - 6x^2 + 1)^3} \cdot 
\left\{
-\frac{(1 + x^2)^3(3x^2 - 1)(x^2 - 4x + 1)(x^2 + 4x + 1) - 4(1 + x^2)^4(x^4 - 6x^2 + 1)}{x^4 - 6x^2 + 1} + 8 (x^4 - 6x^2 + 1)^2
\right\} \\
&= \frac{(1 + x^2)(x^2 - 3)}{(x^4 - 6x^2 + 1)^3} \cdot 
\left\{
-(1 + x^2)^3\frac{(3x^2 - 1)(x^2 - 4x + 1)(x^2 + 4x + 1) - 4(1 + x^2)(x^4 - 6x^2 + 1)}{x^4 - 6x^2 + 1} + 8 (x^4 - 6x^2 + 1)^2
\right\} \\
&= \frac{(1 + x^2)(x^2 - 3)}{(x^4 - 6x^2 + 1)^3} \cdot 
\left\{
-(1 + x^2)^3\frac{- x^6 - 23 x^4 + 37 x^2 - 5}{x^4 - 6x^2 + 1} + 8 (x^4 - 6x^2 + 1)^2
\right\} \\
&= \frac{(1 + x^2)(x^2 - 3)}{(x^4 - 6x^2 + 1)^3} \cdot 
\left\{
(1 + x^2)^3\frac{x^6 + 23 x^4 - 37 x^2 + 5}{x^4 - 6x^2 + 1} + 8 (x^4 - 6x^2 + 1)^2
\right\} \\
&= \frac{(1 + x^2)(x^2 - 3)}{(x^4 - 6x^2 + 1)^3} \cdot 
\left\{
\frac{(1 + x^2)^3(x^6 + 23 x^4 - 37 x^2 + 5) + 8 (x^4 - 6x^2 + 1)^3}{x^4 - 6x^2 + 1} 
\right\} \\
&= \frac{(1 + x^2)(x^2 - 3)}{(x^4 - 6x^2 + 1)^3} \cdot
\frac{9 x^{12} - 118 x^{10} + 923 x^8 - 2052 x^6 + 815 x^4 - 166 x^2 + 13}{x^4 - 6x^2 + 1} \\
\end{align*}
++++
