ifndef::leveloffset[]
:toc: left
:toclevels: 3
:icons: font
:stem: latexmath
endif::[]

ifndef::imagesdir[]
:imagesdir: images
endif::[]

include::header.adoc[]

include::../../attrs.adoc[]

== 微分幾何入門 第一章

=== 問題1.6
問:: 2次元球面(単位球面)
latexmath:[S^2 = \{(\cos \varphi \sin \theta, \sin \varphi \sin \theta, \cos \theta) \in \mathbb{R}^3 | 0 \leq \varphi \leq \pi, 0 \leq \theta \leq 2\pi\}]に対して、座標近傍 latexmath:[(U_i, \varphi_i)]を latexmath:[(\cos \varphi \sin \theta, \sin \varphi \sin \theta, \cos \theta) \mapsto (\varphi, \theta)]となるよう適当な開被覆で覆ってアトラスを構成せよ。また変換関数、 latexmath:[\Psi_{ij}も求めよ]

=== 問題1.7
_T_^2^ に適当なアトラスを定めよ

=== 問題1.10
問::
多様体としての開区間I=(-pi/2, pi/2)とRが微分同相であることを示せ。 +
(I ⊂ R は開区間(a,b)であればなんでもよいことも簡単にわかる)

**回答**

latexmath:[f: I\to \mathbb{R}]の写像に対して、 latexmath:[f(\theta \in I) = \tan\theta]を考えると、__I__から__R__への微分同相写像であることがわかる。

=== 問題1.12 (p21)
問::
例1.8では、latexmath:[\boldsymbol{r}_{(1)}(t)]に沿った接ベクトルが latexmath:[\displaystyle\frac{d}{dt}=\frac{\partial}{\partial\varphi}]、latexmath:[\boldsymbol{r}_{(2)}(t)]に沿った接ベクトルが latexmath:[\displaystyle\frac{d}{dt}=\frac{\partial}{\partial\theta}]であることを確認せよ。

* 点 _p_ を通る緯線 latexmath:[\boldsymbol{r}_{(1)}(t) := (x^1(t), x^2(t), x^3(t)) = (\sin\theta_0 \cos t, \sin\theta_0 \sin t, \cos \theta_0)]
* 点 _p_ を通る経線 latexmath:[\boldsymbol{r}_{(2)}(t) := (x^1(t), x^2(t), x^3(t)) = (\sin t \cos\varphi_0, \sin t \sin\varphi_0, \cos t)]

*回答*

まず、latexmath:[\boldsymbol{r}_{(1)}(t)]、および latexmath:[\boldsymbol{r}_{(2)}(t)] に沿った接ベクトルを求める。

[stem,latexmath]
++++
\begin{aligned}
\frac{d\boldsymbol{r}_{(1)}}{dt}(t)
&= \left(\frac{dx^1(t)}{dt}, \frac{dx^2(t)}{dt}, \frac{dx^3(t)}{dt} \right) \\
&= \left(-\sin\theta_0\sin t, \sin\theta_0\cos t, 0 \right) \\
\end{aligned}
++++

[stem,latexmath]
++++
\begin{aligned}
\frac{d\boldsymbol{r}_{(2)}}{dt}(t)
&= \left(\frac{dx^1(t)}{dt}, \frac{dx^2(t)}{dt}, \frac{dx^3(t)}{dt} \right) \\
&= \left(\cos t \cos\varphi_0, \cos t \sin\varphi_0, -\sin t \right) \\
\end{aligned}
++++

続いて、 latexmath:[\boldsymbol{r}(\theta, \varphi)=(\sin\theta \cos\varphi, \sin\theta \sin\varphi, \cos\theta)]  偏微分を行う。

[stem,latexmath]
++++
\begin{aligned}
\frac{d\boldsymbol{r}(\theta, \varphi)}{dt}
&= \frac{d\theta}{dt}\frac{\partial\boldsymbol{r}}{\partial\theta} + \frac{d\varphi}{dt}\frac{\partial\boldsymbol{r}}{\partial\varphi} \\
&= \frac{d\theta}{dt}(\cos\theta \cos\varphi, \cos\theta \sin\varphi, -\sin\theta) + \frac{d\varphi}{dt}(-\sin\theta \sin\varphi, \sin\theta \cos\varphi, 0) \\
\end{aligned}
++++

この式から、最終的に、 latexmath:[\displaystyle\frac{d}{dt}=\frac{\partial}{\partial\varphi}]、latexmath:[\displaystyle\frac{d}{dt}=\frac{\partial}{\partial\theta}]であることがわかる。
