ifndef::leveloffset[]
:toc: left
:toclevels: 3
:icons: font
:stem: latexmath
endif::[]

ifndef::imagesdir[]
:imagesdir: images
endif::[]

include::header.adoc[]

include::../../attrs.adoc[]

== 微分幾何入門 第二章: 2.1 線素, 面積素, 体積素 (p35-p38)
演習問題の解法の理解を深めるための覚書です。

=== 問題2.1 (p36)
問(1):: ベクトル da=(da^1^, da^2^), db=(db^1^, db^2^)に対して |da^1^ db^2^ - da^2^ db^1^| が平行四辺形の面積であることを示せ

問(1)の解答::
da と db のなす角を _θ_ とすると、面積 _S_ = |da| |db| sin _θ_ になる。
一方で内積は latexmath:[\langle da,db\rangle=|da||db|\cos\theta]となる。 +
面積の両辺を2乗すると、 _S_^2^ = |da|^2^ |db|^2^ sin^2 _θ_ = |da|^2^ |db|^2^ (1 - \cos^2 \theta)となる。
+
[stem,latexmath]
++++
\begin{aligned}
S &= |da||db|\sin\theta \\
S^2 &= |da|^2 |db|^2 \sin^2 \theta = |da|^2 |db|^2 (1 - \cos^2 \theta) \\
&= |da|^2 |db|^2 \left(1 - \frac{\langle da,db\rangle^2}{|da|^2 |db|^2} \right) \\
&= |da|^2 |db|^2 - \langle da,db\rangle^2 \\
&= ((da^1)^2 + (da^2)^2)((db^1)^2 + (db^2)^2) - (da^1 db^1 + da^2 db^2)^2 \\
&= (da^1)^2 (db^1)^2 + (da^1)^2 (db^2)^2 + (da^2)^2 (db^1)^2 + (da^2)^2 (db^2)^2 - (da^1)^2 (db^1)^2 - 2da^1 da^2 db^1 db^2 - (da^2)^2 (db^2)^2 \\
&= (da^1)^2 (db^2)^2 + (da^2)^2 (db^1)^2 - 2da^1 da^2 db^1 db^2 \\
&= \left\{(da^1)(db^2) - (da^2)(db^1)\right\}^2 \\
S &= (da^1)(db^2) - (da^2)(db^1) \\
&= \det\begin{vmatrix}
da^1 & da^2 \\
db^1 & db^2 \\
\end{vmatrix}
\end{aligned}
++++

問(2):: latexmath:[\boldsymbol{x}=(1, 2), \boldsymbol{y}=(2, 3)]の作る平行四辺形の面積を求めよ

問(2)の解答::
S= |1 * 3 - 2 * 2| = 1

=== 問題2.2 (p37)
問:: 式(2.1)の絶対値がユークリッド空間内のベクトル _du_=(_du_^1^, _du_^2^, _du_^3^), _dv_=(_dv_^1^, _dv_^2^, _dv_^3^), _dw_=(_dw_^1^, _dw_^2^, _dw_^3^)が作る平行六面体の体積を与えることを示せ
