ifndef::leveloffset[]
:toc: left
:toclevels: 3
:icons: font
:stem: latexmath
endif::[]

ifndef::imagesdir[]
:imagesdir: images
endif::[]

include::header.adoc[]

include::../../attrs.adoc[]

== 微分幾何入門 第二章: 2.2 外積と外微分 › 2.2.4 外微分 (p49-p52)
演習問題の解法の理解を深めるための覚書です。

=== 定義2.4
局所座標を使い、各点 _p_ の近傍で定義される _k_-形式 latexmath:[\displaystyle \omega = \frac{1}{k!}\omega_{\mu_1\cdots\mu_k} dx_{\mu_1} \wedge \cdots \wedge dx_{\mu_k}]に対して、(_k_+1)形式\(d\omega\)を外微分(exterior derivative) latexmath:[d: \Omega^k(M) \to \Omega^{k+1}(M)]を定義する。

[stem,latexmath]
++++
\begin{aligned}
d \omega
&:= d\left(\frac{1}{k!}\omega_{\mu_1\cdots\mu_k}\right) \wedge dx_{\mu_1} \wedge \cdots \wedge dx_{\mu_k} \\
&= \frac{1}{k!} \frac{\partial \omega_{\mu_1\cdots\mu_k}}{\partial x^{\nu}} d x^{\nu} \wedge dx_{\mu_1} \wedge \cdots \wedge dx_{\mu_k} \\
\end{aligned}
++++

=== 問題2.10 (p50)
問:: latexmath:[\mathbb{R}^2]上で定義された微分形式について、以下を計算せよ。
(1) 0-形式の外微分::: latexmath:[d(x^2 y^3)]
(2) 1-形式の外微分::: latexmath:[d(x^2 y^3 \, dx + x^2 \cos y \, dy)]
(3) 2-形式の外微分::: latexmath:[d(x^2 y^4 \, dx \wedge dy)]

解答::
(1) 0-形式の外微分::: latexmath:[d(x^2 y^3) = 2x y^3 \, dx + 3 x^2 y^3 \, dy]
(1) 0-形式の外微分:::
(別解: 定義2.4を用いて展開する) +
\(\omega = x^2 y^3\) とし、定義2.4を 0-形式に適用する。
+
[stem,latexmath]
++++
\begin{aligned}
d\omega
&= d\left(\frac{1}{0!} \omega \right) \\
&= \frac{\partial \omega}{\partial x^{\nu}} d x^{\nu} \\
&= \frac{\partial \omega}{\partial x^1} d x^1 + \frac{\partial \omega}{\partial x^2} d x^2 \\
\end{aligned}
++++
ここで、座標を \(x^1 = x, x^2 = y\) と取ると、\(dx^1 = dx\) および \(dx^2 = dy\) となる。
+
[stem,latexmath]
++++
\begin{aligned}
&= \frac{\partial \omega}{\partial x} d x + \frac{\partial \omega}{\partial y} d y \\
\end{aligned}
++++
+
これらの偏微分を計算すると、結果は次のようになる。
+
[stem,latexmath]
++++
\begin{aligned}
&= 2x y^3 \, dx + 3 x^2 y^3 \, dy
\end{aligned}
++++

(2) 1-形式の外微分::: latexmath:[d(x^2 y^3 \, dx + x^2 \cos y \, dy)]について計算する。
+
[stem,latexmath]
++++
\begin{aligned}
d(x^2 y^3 \, dx + x^2 \cos y \, dy)
&= d(x^2 y^3 \, dx) + d(x^2 \cos y \, dy) \\
&= \left\{\frac{\partial x^2 y^3}{\partial x}dx + \frac{\partial x^2 y^3}{\partial y}dy \right\} \wedge dx
  + \left\{\frac{\partial x^2 \cos y}{\partial x}dx + \frac{\partial x^2 \cos y}{\partial y}dy \right\} \wedge dy \\
&= \frac{\partial x^2 y^3}{\partial y} \, dy \wedge dx
  + \frac{\partial x^2 \cos y}{\partial x} \, dx \wedge dy \\
&= (3 x^2 y^2) \, dy \wedge dx + (2x \cos y) \, dx \wedge dy \\
&= (-3 x^2 y^2  + 2x \cos y) \, dx \wedge dy \\
\end{aligned}
++++

(2) 1-形式の外微分:::
(別解: 定義2.4を用いて展開する) +
\(\omega = x^2 y^3 \, dx + x^2 \cos y \, dy\)、\(\omega_1 = x^2 y^3\)、および \(\omega_2 = x^2 \cos y\) とし、定義2.4を 1-形式に適用する。なお、\(\omega_{\mu}\) は係数関数であり、\(\omega_1, \omega_2\) に対応する。
+
[stem,latexmath]
++++
\begin{aligned}
d\omega
&= d (\omega_{\mu} \, dx^{\mu})\\
&= \frac{\partial \omega_{\mu}}{\partial x^{\nu}} \, d x^{\nu} \wedge d x^{\mu} \\
&= \frac{\partial \omega_1}{\partial x^1} \, d x^1 \wedge d x^1
  + \frac{\partial \omega_2}{\partial x^1} \, d x^1 \wedge d x^2 
  + \frac{\partial \omega_1}{\partial x^2} \, d x^2 \wedge d x^1
  + \frac{\partial \omega_2}{\partial x^2} \, d x^2 \wedge d x^2 \\
\end{aligned}
++++
+
ウェッジ積の反対称性により、\(dx^1 \wedge dx^1 = dx^2 \wedge dx^2 = 0\) だから、残るのは2項だけである。
+
[stem,latexmath]
++++
\begin{aligned}
&= \frac{\partial \omega_2}{\partial x^1} \, d x^1 \wedge d x^2 
  + \frac{\partial \omega_1}{\partial x^2} \, d x^2 \wedge d x^1 \\
\end{aligned}
++++
+
ウェッジ積の反対称性により、添え字を入れ替えると符号が反転することを踏まえて、添え字を揃えると次のようになる。
+
[stem,latexmath]
++++
\begin{aligned}
&= \left(\frac{\partial \omega_2}{\partial x^1} - \frac{\partial \omega_1}{\partial x^2}\right) \, d x^1 \wedge d x^2 \\
\end{aligned}
++++
+
ここで、座標を \(x^1 = x, x^2 = y\) と取ると、\(dx^1 = dx\) および \(dx^2 = dy\) となる。
+
[stem,latexmath]
++++
\begin{aligned}
&= \left(\frac{\partial \omega_2}{\partial x} - \frac{\partial \omega_1}{\partial y}\right) \, dx \wedge dy \\
\end{aligned}
++++
+
これらの偏微分を計算すると、結果は次のようになる。
+
[stem,latexmath]
++++
\begin{aligned}
&= (-3 x^2 y^2  + 2x \cos y) \, dx \wedge dy
\end{aligned}
++++

(3) 2-形式の外微分::: ウェッジ積の反対称性により、latexmath:[d(x^2 y^4 \, dx \wedge dy)=0]となることを示す。
+
\(x^2 y^4 \, dx \wedge dy\)、\(\omega_{1 2} = x^2 y^4, \, \omega_{2 1}= -\omega_{1 2}, \, \omega_{1 1}=\omega_{2 2}=0\) とし、定義2.4を 2-形式に適用する。なお、\(\omega_{\mu_1\mu_2}\) は係数関数であり、\(\omega_{1 2}\) などに対応する。
+
[stem,latexmath]
++++
\begin{aligned}
d\omega
&= d \left(\frac{1}{2} \omega_{\mu_1\mu_2} \, dx^{\mu_1} \wedge dx^{\mu_2}\right) \\
&= \frac{\partial \omega_{\mu_1\mu_2}}{\partial x^{\nu}} \, d x^{\nu} \wedge d x^{\mu_1} \wedge d x^{\mu_2} \\
\end{aligned}
++++
+
まず、\(\mu \in\{1, 2\}\)、具体的には\(\mu=1\), \(\mu=2\)に対してアインシュタイン縮約記法を展開すると次のようになる。
+
[stem,latexmath]
++++
\begin{aligned}
&= \frac{\partial \omega_{1 1}}{\partial x^\nu} \, d x^{\nu} \wedge d x^1 \wedge d x^1
  + \frac{\partial \omega_{1 2}}{\partial x^\nu} \, d x^{\nu} \wedge d x^1 \wedge d x^2 
  + \frac{\partial \omega_{2 1}}{\partial x^\nu} \, d x^{\nu} \wedge d x^2 \wedge d x^1
  + \frac{\partial \omega_{2 2}}{\partial x^\nu} \, d x^{\nu} \wedge d x^2 \wedge d x^2 \\
\end{aligned}
++++
+
ウェッジ積の反対称性により、\(dx^1 \wedge dx^1 = dx^2 \wedge dx^2 = 0\) だから、残るのは2項だけである。
+
[stem,latexmath]
++++
\begin{aligned}
&= \frac{\partial \omega_{1 2}}{\partial x^\nu} \, d x^{\nu} \wedge d x^1 \wedge d x^2 
  + \frac{\partial \omega_{2 1}}{\partial x^\nu} \, d x^{\nu} \wedge d x^2 \wedge d x^1 \\
\end{aligned}
++++
+
\(\nu \in\{1, 2\}\)、具体的には\(\nu=1\), \(\nu=2\)に対してアインシュタイン縮約記法を展開し、最終的にウェッジ積の反対称性により、\(dx^1 \wedge dx^1 \wedge dx^2 = 0\)、\(dx^2 \wedge dx^1 \wedge dx^1 = 0\) など、すべての項に同じ因子が含まれるため 0 になる。
+
[stem,latexmath]
++++
\begin{aligned}
&= \frac{\partial \omega_{1 2}}{\partial x^1} \, d x^1 \wedge d x^1 \wedge d x^2 
  + \frac{\partial \omega_{1 2}}{\partial x^2} \, d x^2 \wedge d x^1 \wedge d x^2 \\
& + \frac{\partial \omega_{2 1}}{\partial x^1} \, d x^1 \wedge d x^2 \wedge d x^1
  + \frac{\partial \omega_{2 1}}{\partial x^2} \, d x^2 \wedge d x^2 \wedge d x^1 \\
&= 0
\end{aligned}
++++

=== 問題2.11 (p52)
問:: latexmath:[\mathbb{R}^3]の1-形式 latexmath:[\omega = y^2 \sin x \cos z \, dx + y \, dy,\ \xi = x \, dz]に対して、以下の計算をせよ。
(1)::: 符号付きライプニッツ則を用いて、 latexmath:[d(\omega \wedge \xi)]を求めよ。
(2)::: 直接計算で latexmath:[dd\omega]が0になることを示せ。

解答::
(1) 符号付きライプニッツ則を用いて、 latexmath:[d(\omega \wedge \xi)]を求めよ。::: 
+
[stem,latexmath]
++++
\begin{aligned}
d(\omega \wedge \xi)
&= d\omega \wedge \xi + (-1)^3 \omega \wedge d\xi \\
&= d(y^2 \sin x \cos z \, dx + y \, dy) \wedge (x \, dz) - (y^2 \sin x \cos z \, dx + y \, dy) \wedge d(x \, dz) \\
&= x \left\{d(y^2 \sin x \cos z \, dx) + d(y \, dy)\right\} \wedge dz \\
& - (y^2 \sin x \cos z \, dx + y \, dy) \wedge \left\{\left(\frac{\partial x}{\partial x}dx + \frac{\partial x}{\partial y}dy + \frac{\partial x}{\partial z}dz \right) \wedge dz \right\} \\
&= x \left\{
   \left(
      \frac{\partial y^2 \sin x \cos z}{\partial x} \, dx
   + \frac{\partial y^2 \sin x \cos z}{\partial y} \, dy
   + \frac{\partial y^2 \sin x \cos z}{\partial z} \, dz
   \right) \wedge dx
   + \left(
      \frac{\partial y}{\partial x}dx
   + \frac{\partial y}{\partial y}dy
   + \frac{\partial y}{\partial z}dz
   \right) \wedge dy
\right\} \wedge dz \\
& - (y^2 \sin x \cos z \, dx + y \, dy) \wedge \left\{\left(\frac{\partial x}{\partial x}dx + \frac{\partial x}{\partial y}dy + \frac{\partial x}{\partial z}dz \right) \wedge dz \right\} \\
&= x \left(
      \frac{\partial y^2 \sin x \cos z}{\partial y} \, dy \wedge dx
   + \frac{\partial y^2 \sin x \cos z}{\partial z} \, dz \wedge dx
   + \frac{\partial y}{\partial x} \, dx \wedge dy
   + \frac{\partial y}{\partial z} \, dz \wedge dy
\right) \wedge dz \\
& - (y^2 \sin x \cos z \, dx + y \, dy) \wedge \left(\frac{\partial x}{\partial x} \, dx \wedge dz + \frac{\partial x}{\partial y} \, dy \wedge dz  \right) \\
&= x \left\{(2y \sin x \cos z) \, dy \wedge \, dx - (y^2 \sin x \sin z) \, dz \wedge dx \right\} \wedge dz
   - (y^2 \sin x \cos z \, dx + y \, dy) \wedge dx \wedge dz \\
&= x(2y \sin x \cos z) \, dy \wedge \, dx \wedge dz - y \, dy \wedge dx \wedge dz \\
&= -2xy \sin x \cos z \, dx \wedge \, dy \wedge dz + y \, dx \wedge dy \wedge dz \\
&= (-2xy \sin x \cos z + y)\, dx \wedge \, dy \wedge dz
\end{aligned}
++++

(2)直接計算で latexmath:[dd\omega]が0になることを示せ。:::
\(dd\omega\)を展開すると次のようになる。 \(\omega\)は _C_^2^ 級で連続であるから、 \(dd\omega=0\)となる。
+
[stem,latexmath]
++++
\begin{aligned}
dd(\omega) &= d(d\omega) \\
&= d\left(
   \frac{\partial \omega}{\partial x} \, dx
   + \frac{\partial \omega}{\partial y} \, dy
   + \frac{\partial \omega}{\partial z} \, dz
\right) \\
&= d\left(\frac{\partial \omega}{\partial x} \, dx \right)
  + d\left(\frac{\partial \omega}{\partial y} \, dy \right)
  + d\left(\frac{\partial \omega}{\partial z} \, dz \right) \\
&= d\left(\frac{\partial \omega}{\partial x} \right) \wedge dx
  + d\left(\frac{\partial \omega}{\partial y} \right) \wedge dy
  + d\left(\frac{\partial \omega}{\partial z} \right) \wedge dz \\
&=
\left(
      \frac{\partial}{\partial x} \frac{\partial \omega}{\partial x} \, dx
   +  \frac{\partial}{\partial y} \frac{\partial \omega}{\partial x} \, dy
   +  \frac{\partial}{\partial z} \frac{\partial \omega}{\partial x} \, dz
\right) \wedge dx \\
& + \left(
      \frac{\partial}{\partial x} \frac{\partial \omega}{\partial y} \, dx
   + \frac{\partial}{\partial y} \frac{\partial \omega}{\partial y} \, dy
   + \frac{\partial}{\partial z} \frac{\partial \omega}{\partial y} \, dz
\right) \wedge dy \\
& + \left(
      \frac{\partial}{\partial x} \frac{\partial \omega}{\partial z} \, dx
   + \frac{\partial}{\partial y} \frac{\partial \omega}{\partial z} \, dy
   + \frac{\partial}{\partial z} \frac{\partial \omega}{\partial z} \, dz
\right) \wedge dz \\
&= \frac{\partial^2 \omega}{\partial y \partial x} \, dy \wedge dx
   + \frac{\partial^2 \omega}{\partial z \partial x} \, dz \wedge dx
   + \frac{\partial^2 \omega}{\partial x \partial y} \, dx \wedge dy
   + \frac{\partial^2 \omega}{\partial z \partial y} \, dz \wedge dy
   + \frac{\partial^2 \omega}{\partial x \partial z} \, dx \wedge dz
   + \frac{\partial^2 \omega}{\partial y \partial z} \, dy \wedge dz \\
&=
\left(
   \frac{\partial^2 \omega}{\partial x \partial y} - \frac{\partial^2 \omega}{\partial y \partial x}
\right) \, dx \wedge dy
+ \left(
   \frac{\partial^2 \omega}{\partial y \partial z} - \frac{\partial^2 \omega}{\partial z \partial y}
\right) \, dy \wedge dz
+ \left(
   \frac{\partial^2 \omega}{\partial z \partial x} - \frac{\partial^2 \omega}{\partial x \partial z}
\right) \, dz \wedge dx \\
\end{aligned}
++++

(2)直接計算で latexmath:[dd\omega]が0になることを示せ。:::
別解。具体的に偏微分してゼロになることを確認します。
+
[stem,latexmath]
++++
\begin{aligned}
dd(\omega) &= d(d\omega) = d(d(y^2 \sin x \cos z \, dx + y \, dy))\\
&= d((y^2 \cos x \cos z \, dx + 2y \sin x \cos z \, dy - y^2 \sin x \sin z \, dz) \wedge dx + (1 \cdot dy) \wedge dy) \\
&= d(2y \sin x \cos z \, dy \wedge dx - y^2 \sin x \sin z \, dz \wedge dx) \\
&= d(- 2y \sin x \cos z \, dx \wedge dy + y^2 \sin x \sin z \, dx \wedge dz) \\
&= (- 2y \cos x \cos z \, dx - 2 \sin x \cos z \, dy + 2y \sin x \sin z \, dz) \wedge dx \wedge dy \\
& + (- y^2 \cos x \sin z \, dx + 2y \sin x \sin z \, dy + y^2 \sin x \cos z \, dz) \wedge dx \wedge dz \\
&= 2y \sin x \sin z \, dz \wedge dx \wedge dy + 2y \sin x \sin z \, dy \wedge dx \wedge dz \\
&= 2y \sin x \sin z \, dx \wedge dy \wedge dz - 2y \sin x \sin z \, dx \wedge dy \wedge dz \\
&= 0 \\
\end{aligned}
++++
