ifndef::leveloffset[]
:toc: left
:toclevels: 3
:icons: font
:stem: latexmath
endif::[]

ifndef::imagesdir[]
:imagesdir: images
endif::[]

include::header.adoc[]

include::../../attrs.adoc[]

== 微分幾何入門 第二章: 2.2 外積と外微分 › 2.2.5 局所座標を用いない定義 (p52-p57)
演習問題の解法の理解を深めるための覚書です。

=== 2.2.5 局所座標を用いない定義 (p53-p57)

====  2-形式の例(p53)

latexmath:[\displaystyle \omega=\frac{1}{2}\omega_{\mu\nu} d x^\mu \wedge d x^\nu]と二つのベクトル場 latexmath:[\displaystyle X_1 = X_1^{\nu}\frac{\partial}{\partial x^\nu}, X_2 = X_2^{\nu} \frac{\partial}{\partial x^\nu}]に対して、双対ペアリングが双線形写像であることを使う。

[stem,latexmath]
++++
\begin{aligned}
\omega(X_1, X_2) 
&= \frac{1}{2}\omega_{\mu\nu} \; d x^\mu \wedge d x^\nu \left(X_1^{\rho} \frac{\partial}{\partial x^\rho}, X_2^{\tau} \frac{\partial}{\partial x^\tau} \right) \\
&= \frac{1}{2}\omega_{\mu\nu} X_1^{\rho} X_2^{\tau} \; d x^\mu \wedge d x^\nu \left(\frac{\partial}{\partial x^\rho}, \frac{\partial}{\partial x^\tau}\right) \\
\end{aligned}
++++

ここで、テンソル積の定義から latexmath:[dx^\mu \wedge dx^\nu = dx^\mu \otimes dx^\nu - dx^\nu \otimes dx^\mu]であり、合わせてテンソル積の評価 latexmath:[(\alpha \otimes \beta)(X, Y) = \alpha (X) \beta (Y)]であるから、次のようになる。

[stem,latexmath]
++++
\begin{aligned}
d x^\mu \wedge d x^\nu \left(\frac{\partial}{\partial x^\rho}, \frac{\partial}{\partial x^\tau}\right)
&= dx^\mu \otimes dx^\nu \left(\frac{\partial}{\partial x^\rho}, \frac{\partial}{\partial x^\tau}\right) - dx^\nu \otimes dx^\mu \left(\frac{\partial}{\partial x^\rho}, \frac{\partial}{\partial x^\tau}\right) \\
&=
  dx^\mu \left(\frac{\partial}{\partial x^\rho}\right)
  dx^\nu \left(\frac{\partial}{\partial x^\tau}\right)
- dx^\nu \left(\frac{\partial}{\partial x^\rho}\right)
  dx^\mu \left(\frac{\partial}{\partial x^\tau}\right) \\
\end{aligned}
++++

双対基底より、latexmath:[dx^\mu \left(\frac{\partial}{\partial x^\rho}\right) = \delta_\rho^\mu], latexmath:[dx^\nu \left(\frac{\partial}{\partial x^\tau}\right) = \delta_\tau^\nu] だから、次のようになる。

[stem,latexmath]
++++
d x^\mu \wedge d x^\nu \left(\frac{\partial}{\partial x^\rho}, \frac{\partial}{\partial x^\tau}\right)
= \delta_\rho^\mu \delta_\tau^\nu - \delta_\rho^\nu \delta_\tau^\mu \\
++++

ここまでを元の式に代入すると、次のようになる。

[stem,latexmath]
++++
\begin{aligned}
\omega(X_1, X_2) 
&= \frac{1}{2}\omega_{\mu\nu} \; d x^\mu \wedge d x^\nu \left(X_1^{\rho} \frac{\partial}{\partial x^\rho}, X_2^{\tau} \frac{\partial}{\partial x^\tau}\right) \\
&= \frac{1}{2}\omega_{\mu\nu} X_1^{\rho} X_2^{\tau} \; d x^\mu \wedge d x^\nu (\frac{\partial}{\partial x^\rho}, \frac{\partial}{\partial x^\tau}) \\
&= \frac{1}{2}\omega_{\mu\nu} X_1^{\rho} X_2^{\tau} (\delta_\rho^\mu \delta_\tau^\nu - \delta_\rho^\nu \delta_\tau^\mu) \\
&= \frac{1}{2}\omega_{\mu\nu} ( X_1^{\mu} X_2^{\nu} - X_1^{\nu} X_2^{\mu}) \\
\end{aligned}
++++

2形式の成分は反対称であるから、次のものが導き出される。

[stem,latexmath]
++++
\begin{aligned}
\omega(X_1, X_2) 
&= \frac{1}{2}\omega_{\mu\nu} (X_1^{\mu} X_2^{\nu} + X_1^{\mu} X_2^{\nu}) \\
&= \omega_{\mu\nu}X_1^{\mu} X_2^{\nu}
\end{aligned}
++++

====  3-形式の例(p53)
3-形式 latexmath:[\displaystyle \omega=\frac{1}{3!}\omega_{\mu\nu\rho} d x^\mu \wedge d x^\nu \wedge d x^\rho]と3つのベクトル場 latexmath:[\displaystyle X_i = X_i^\nu \frac{\partial}{\partial x^\nu}\, (i=1,2,3)]から、双対ペアリングを多重線形写像に拡張した関数を得られる。

[stem,latexmath]
++++
\begin{aligned}
\omega(X_1, X_2, X_3) 
&= \frac{1}{3!}\omega_{\mu_1\mu_2\mu_3} \; d x^{\mu_1} \wedge d x^{\mu_2} \wedge d x^{\mu_3} \left(X_1^{\nu_1} \frac{\partial}{\partial x^{\nu_1}}, X_2^{\nu_2} \frac{\partial}{\partial x^{\nu_2}}, X_3^{\nu_3} \frac{\partial}{\partial x^{\nu_3}} \right) \\
&= \frac{1}{3!}\omega_{\mu_1\mu_2\mu_3} X_1^{\nu_1} X_2^{\nu_2} X_3^{\nu_3} \; d x^{\mu_1} \wedge d x^{\mu_2} \wedge d x^{\mu_3} \left( \frac{\partial}{\partial x^{\nu_1}}, \frac{\partial}{\partial x^{\nu_2}}, \frac{\partial}{\partial x^{\nu_3}} \right) \\
\end{aligned}
++++

ここで、テンソル積の定義から 3-形式は次のように定義できる。
[stem,latexmath]
++++
\begin{aligned}
dx^{\mu_1} \wedge dx^{\mu_2} \wedge dx^{\mu_3}
&:= \sum_{\sigma \in S_3}\mathrm{sgn}
\begin{pmatrix}
\mu_1 & \mu_2 & \mu_3 \\
\sigma(\mu_1) & \sigma(\mu_2) & \sigma(\mu_3) \\ 
\end{pmatrix}
dx^{\sigma(\mu_1)} \otimes dx^{\sigma(\mu_2)} \otimes dx^{\sigma(\mu_3)} \\
\end{aligned}
++++

合わせてテンソル積の評価 latexmath:[(\alpha \otimes \beta \otimes \gamma)(X, Y, Z) = \alpha (X) \beta (Y) \gamma(Z)]であるから、次のようになる。

[stem,latexmath]
++++
\begin{aligned}
dx^{\mu_1} \wedge dx^{\mu_2} \wedge dx^{\mu_3}
\, \left(
  \frac{\partial}{\partial \nu_1},
  \frac{\partial}{\partial \nu_2},
  \frac{\partial}{\partial \nu_3}
\right)
&= \sum_{\sigma \in S_3}\mathrm{sgn}
\begin{pmatrix}
\mu_1 & \mu_2 & \mu_3 \\
\sigma(\mu_1) & \sigma(\mu_2) & \sigma(\mu_3) \\ 
\end{pmatrix}
dx^{\sigma(\mu_1)} \otimes dx^{\sigma(\mu_2)} \otimes dx^{\sigma(\mu_3)} \\
&= \sum_{\sigma \in S_3}\mathrm{sgn}
\begin{pmatrix}
\mu_1 & \mu_2 & \mu_3 \\
\sigma(\mu_1) & \sigma(\mu_2) & \sigma(\mu_3) \\ 
\end{pmatrix}
dx^{\sigma(\mu_1)} \left(\frac{\partial}{\partial x^{\nu_1}}\right)
dx^{\sigma(\mu_2)} \left(\frac{\partial}{\partial x^{\nu_2}}\right)
dx^{\sigma(\mu_3)} \left(\frac{\partial}{\partial x^{\nu_3}}\right) \\
&= \sum_{\sigma \in S_3}\mathrm{sgn}
\begin{pmatrix}
\mu_1 & \mu_2 & \mu_3 \\
\sigma(\mu_1) & \sigma(\mu_2) & \sigma(\mu_3) \\ 
\end{pmatrix}
\delta^{\sigma(\mu_1)}_{\nu_1}
\delta^{\sigma(\mu_2)}_{\nu_2}
\delta^{\sigma(\mu_3)}_{\nu_3} \\
\end{aligned}
++++

ここまでを元の式に代入すると、次のようになる。

[stem,latexmath]
++++
\begin{aligned}
\omega(X_1, X_2, X_3) 
&= \frac{1}{3!}\omega_{\mu_1\mu_2\mu_3} \; d x^{\mu_1} \wedge d x^{\mu_2} \wedge d x^{\mu_3} \left(X_1^{\nu_1} \frac{\partial}{\partial x^{\nu_1}}, X_2^{\nu_2} \frac{\partial}{\partial x^{\nu_2}}, X_3^{\nu_3} \frac{\partial}{\partial x^{\nu_3}} \right) \\
&= \frac{1}{3!}\omega_{\mu_1\mu_2\mu_3} X_1^{\nu_1} X_2^{\nu_2} X_3^{\nu_3} \; d x^{\mu_1} \wedge d x^{\mu_2} \wedge d x^{\mu_3} \left( \frac{\partial}{\partial x^{\nu_1}}, \frac{\partial}{\partial x^{\nu_2}}, \frac{\partial}{\partial x^{\nu_3}} \right) \\
&= \frac{1}{3!}\omega_{\mu_1\mu_2\mu_3} X_1^{\nu_1} X_2^{\nu_2} X_3^{\nu_3} \;
\sum_{\sigma \in S_3}\mathrm{sgn}
\begin{pmatrix}
\mu_1 & \mu_2 & \mu_3 \\
\sigma(\mu_1) & \sigma(\mu_2) & \sigma(\mu_3) \\ 
\end{pmatrix}
\delta^{\sigma(\mu_1)}_{\nu_1}
\delta^{\sigma(\mu_2)}_{\nu_2}
\delta^{\sigma(\mu_3)}_{\nu_3} \\
&= \frac{1}{3!}
\sum_{\sigma \in S_3}\mathrm{sgn}
\begin{pmatrix}
\mu_1 & \mu_2 & \mu_3 \\
\sigma(\mu_1) & \sigma(\mu_2) & \sigma(\mu_3) \\ 
\end{pmatrix}
\omega_{\mu_1\mu_2\mu_3} X_1^{\sigma(\mu_1)} X_2^{\sigma(\mu_2)} X_3^{\sigma(\mu_3)} \\
&= \frac{1}{3!}\sum_{\sigma\in S_3}\mathrm{sgn}(\sigma)\,\omega_{\mu_1\mu_2\mu_3}\,X_1^{\sigma(\mu_1)}X_2^{\sigma(\mu_2)}X_3^{\sigma(\mu_3)} \\
&= \frac{1}{3!}\sum_{\sigma\in S_3}\omega_{\sigma(\mu_1)\sigma(\mu_2)\sigma(\mu_3)}\,X_1^{\mu_1}X_2^{\mu_2}X_3^{\mu_3} \quad(\text{index relabelling }\mu_i\mapsto\sigma(\mu_i))\\
&= \frac{1}{3!}\sum_{\sigma\in S_3}\omega_{\mu_1\mu_2\mu_3}\,X_1^{\mu_1}X_2^{\mu_2}X_3^{\mu_3} \quad(\omega\ \text{is antisymmetric})\\
&= \omega_{\mu_1\mu_2\mu_3}\,X_1^{\mu_1}X_2^{\mu_2}X_3^{\mu_3}
\end{aligned}
++++

ここで、最後の等式は、添え字に対する完全反対称の性質をもつため、次のようになる。

[stem,latexmath]
++++
\begin{aligned}
&= \frac{1}{3!}
\left\{
   \omega_{\mu_1\mu_2\mu_3} X_1^{\sigma(\mu_1)} X_2^{\sigma(\mu_2)} X_3^{\sigma(\mu_3)}
- \omega_{\mu_1\mu_3\mu_2} X_1^{\sigma(\mu_1)} X_2^{\sigma(\mu_3)} X_3^{\sigma(\mu_2)} \\
- \omega_{\mu_2\mu_1\mu_3} X_1^{\sigma(\mu_2)} X_2^{\sigma(\mu_1)} X_3^{\sigma(\mu_3)}
+ \omega_{\mu_2\mu_3\mu_1} X_1^{\sigma(\mu_2)} X_2^{\sigma(\mu_3)} X_3^{\sigma(\mu_1)} \\
+ \omega_{\mu_3\mu_1\mu_2} X_1^{\sigma(\mu_3)} X_2^{\sigma(\mu_1)} X_3^{\sigma(\mu_2)}
- \omega_{\mu_3\mu_2\mu_1} X_1^{\sigma(\mu_3)} X_2^{\sigma(\mu_2)} X_3^{\sigma(\mu_1)}
\right\} \\
&= \frac{1}{3!}
\left\{
   \omega_{\mu_1\mu_2\mu_3} X_1^{\sigma(\mu_1)} X_2^{\sigma(\mu_2)} X_3^{\sigma(\mu_3)}
+ \omega_{\mu_1\mu_2\mu_3} X_1^{\sigma(\mu_1)} X_2^{\sigma(\mu_2)} X_3^{\sigma(\mu_3)} \\
+ \omega_{\mu_1\mu_2\mu_3} X_1^{\sigma(\mu_1)} X_2^{\sigma(\mu_2)} X_3^{\sigma(\mu_3)}
+ \omega_{\mu_2\mu_3\mu_1} X_1^{\sigma(\mu_2)} X_2^{\sigma(\mu_3)} X_3^{\sigma(\mu_1)} \\
+ \omega_{\mu_3\mu_1\mu_2} X_1^{\sigma(\mu_3)} X_2^{\sigma(\mu_1)} X_3^{\sigma(\mu_2)}
+ \omega_{\mu_1\mu_2\mu_3} X_1^{\sigma(\mu_1)} X_2^{\sigma(\mu_2)} X_3^{\sigma(\mu_3)}
\right\} \\
&= \omega_{\mu_1\mu_2\mu_3} X_1^{\sigma(\mu_1)} X_2^{\sigma(\mu_2)} X_3^{\sigma(\mu_3)}
\end{aligned}
++++


=== 問題2.12 (p54)
問:: 式(2.12)を示せ。

=== 問題2.13 (p56)
問:: 座標を使った外微分の定義(2.9)が、上の座標を用いない外微分の定義式(2.13)を満たすことを示せ。
