ifndef::leveloffset[]
:toc: left
:toclevels: 3
:icons: font
:stem: latexmath
endif::[]

ifndef::imagesdir[]
:imagesdir: images
endif::[]

include::header.adoc[]

include::../../attrs.adoc[]

== 微分幾何入門 第二章: 2.2 外積と外微分 › 2.2.5 局所座標を用いない定義 (p52-p57)
演習問題の解法の理解を深めるための覚書です。

=== 2.2.5 局所座標を用いない定義 (p53-p57)

====  2-形式の例(p53)

latexmath:[\displaystyle \omega=\frac{1}{2}\omega_{\mu\nu} d x^\mu \wedge d x^\nu]と二つのベクトル場 latexmath:[\displaystyle X_1 = X_1^{\nu}\frac{\partial}{\partial x^\nu}, X_2 = X_2^{\nu} \frac{\partial}{\partial x^\nu}]に対して、双対ペアリングが双線形写像であることを使う。

[stem,latexmath]
++++
\begin{aligned}
\omega(X_1, X_2) 
&= \frac{1}{2}\omega_{\mu\nu} \; d x^\mu \wedge d x^\nu \left(X_1^{\rho} \frac{\partial}{\partial x^\rho}, X_2^{\tau} \frac{\partial}{\partial x^\tau} \right) \\
&= \frac{1}{2}\omega_{\mu\nu} X_1^{\rho} X_2^{\tau} \; d x^\mu \wedge d x^\nu \left(\frac{\partial}{\partial x^\rho}, \frac{\partial}{\partial x^\tau}\right) \\
\end{aligned}
++++

ここで、テンソル積の定義から latexmath:[dx^\mu \wedge dx^\nu = dx^\mu \otimes dx^\nu - dx^\nu \otimes dx^\mu]であり、合わせてテンソル積の評価 latexmath:[(\alpha \otimes \beta)(X, Y) = \alpha (X) \beta (Y)]であるから、次のようになる。

[stem,latexmath]
++++
\begin{aligned}
d x^\mu \wedge d x^\nu \left(\frac{\partial}{\partial x^\rho}, \frac{\partial}{\partial x^\tau}\right)
&= dx^\mu \otimes dx^\nu \left(\frac{\partial}{\partial x^\rho}, \frac{\partial}{\partial x^\tau}\right) - dx^\nu \otimes dx^\mu \left(\frac{\partial}{\partial x^\rho}, \frac{\partial}{\partial x^\tau}\right) \\
&=
  dx^\mu \left(\frac{\partial}{\partial x^\rho}\right)
  dx^\nu \left(\frac{\partial}{\partial x^\tau}\right)
- dx^\nu \left(\frac{\partial}{\partial x^\rho}\right)
  dx^\mu \left(\frac{\partial}{\partial x^\tau}\right) \\
\end{aligned}
++++

双対基底より、latexmath:[dx^\mu \left(\frac{\partial}{\partial x^\rho}\right) = \delta_\rho^\mu], latexmath:[dx^\nu \left(\frac{\partial}{\partial x^\tau}\right) = \delta_\tau^\nu] だから、次のようになる。

[stem,latexmath]
++++
d x^\mu \wedge d x^\nu \left(\frac{\partial}{\partial x^\rho}, \frac{\partial}{\partial x^\tau}\right)
= \delta_\rho^\mu \delta_\tau^\nu - \delta_\rho^\nu \delta_\tau^\mu \\
++++

ここまでを元の式に代入すると、次のようになる。

[stem,latexmath]
++++
\begin{aligned}
\omega(X_1, X_2) 
&= \frac{1}{2}\omega_{\mu\nu} \; d x^\mu \wedge d x^\nu \left(X_1^{\rho} \frac{\partial}{\partial x^\rho}, X_2^{\tau} \frac{\partial}{\partial x^\tau}\right) \\
&= \frac{1}{2}\omega_{\mu\nu} X_1^{\rho} X_2^{\tau} \; d x^\mu \wedge d x^\nu \left(\frac{\partial}{\partial x^\rho}, \frac{\partial}{\partial x^\tau}\right) \\
&= \frac{1}{2}\omega_{\mu\nu} X_1^{\rho} X_2^{\tau} \left(\delta_\rho^\mu \delta_\tau^\nu - \delta_\rho^\nu \delta_\tau^\mu\right) \\
&= \frac{1}{2}\omega_{\mu\nu} \left( X_1^{\mu} X_2^{\nu} - X_1^{\nu} X_2^{\mu}\right) \\
&= \frac{1}{2}\left(\omega_{\mu\nu} X_1^{\mu} X_2^{\nu} - \omega_{\mu\nu} X_1^{\nu} X_2^{\mu}\right) \\
\end{aligned}
++++

後半の項のダミー添字を latexmath:[\mu \leftrightarrow \nu]の入れ替えを行うと、

[stem,latexmath]
++++
\begin{aligned}
&= \frac{1}{2} \left( \omega_{\mu\nu} X_1^{\mu} X_2^{\nu} - \omega_{\nu\mu} X_1^{\mu} X_2^{\nu} \right) \\
\end{aligned}
++++

2-形式の係数の反対称性 latexmath:[\omega_{\nu\mu} = - \omega_{\mu\nu}]を使うと第二項の符号が反転し、これで二項が同じになり latexmath:[\frac{1}{2}]が消えて、次の結果が得られる。

[stem,latexmath]
++++
\begin{aligned}
&= \frac{1}{2} \left( \omega_{\mu\nu} X_1^{\mu} X_2^{\nu} + \omega_{\mu\nu} X_1^{\mu} X_2^{\nu}\right) \\
&= \omega_{\mu\nu} X_1^{\mu} X_2^{\nu} \\
\end{aligned}
++++

====  2-形式の例(p53): sgnを使う場合

テンソル積の定義から 2-形式 は、latexmath:[\mu \lt \nu]として、次のように定義される。ここでは 2次元基底 latexmath:[x^1], latexmath:[x^2] を固定しているので、latexmath:[\mu], latexmath:[\nu] は 1, 2 の値をとるラベルとして扱い、和の省略は明示的に「同じ添字が 2回現れるとき」のみ適用する。

[stem,latexmath]
++++
\begin{aligned}
dx^{\mu} \wedge dx^{\nu}
&= dx^{\mu} \otimes dx^{\nu} - dx^{\nu} \otimes dx^{\mu} \\
&= \sum_{\sigma \in S_2}\mathrm{sgn}
\begin{pmatrix}
\mu & \nu \\
\sigma(\mu) & \sigma(\nu) \\ 
\end{pmatrix}
dx^{\sigma(\mu)} \otimes dx^{\sigma(\nu)}
\end{aligned}
++++

合わせてテンソル積の評価 latexmath:[(\alpha \otimes \beta)(X, Y) = \alpha (X) \beta (Y)]であるから、次のようになる。

[stem,latexmath]
++++
\begin{aligned}
& dx^{\mu} \wedge dx^{\nu}
\, \left(
  \frac{\partial}{\partial x^{\rho}},
  \frac{\partial}{\partial x^{\tau}}
\right) \\
&= \sum_{\sigma \in S_2}\mathrm{sgn}
\begin{pmatrix}
\mu & \nu \\
\sigma(\mu) & \sigma(\nu) \\ 
\end{pmatrix}
dx^{\sigma(\mu)} \otimes dx^{\sigma(\nu)}
\, \left(
  \frac{\partial}{\partial x^{\rho}},
  \frac{\partial}{\partial x^{\tau}}
\right) \\
&= \sum_{\sigma \in S_2}\mathrm{sgn}
\begin{pmatrix}
\mu & \nu \\
\sigma(\mu) & \sigma(\nu) \\ 
\end{pmatrix}
dx^{\sigma(\mu)} \left(\frac{\partial}{\partial x^{\rho}}\right)
dx^{\sigma(\nu)} \left(\frac{\partial}{\partial x^{\tau}}\right) \\
&= \sum_{\sigma \in S_2}\mathrm{sgn}
\begin{pmatrix}
\mu & \nu \\
\sigma(\mu) & \sigma(\nu) \\ 
\end{pmatrix}
\delta^{\sigma(\mu)}_{\rho}
\delta^{\sigma(\nu)}_{\tau} \\
\end{aligned}
++++

ここまでを元の式に代入すると、次のようになる。

[stem,latexmath]
++++
\begin{aligned}
\omega(X_1, X_2)
&= \frac{1}{2}\omega_{\mu\nu} \; d x^\mu \wedge d x^\nu \left(X_1^{\rho} \frac{\partial}{\partial x^\rho}, X_2^{\tau} \frac{\partial}{\partial x^\tau}\right) \\
&= \frac{1}{2}\omega_{\mu\nu} X_1^{\rho} X_2^{\tau} \; d x^\mu \wedge d x^\nu \left(\frac{\partial}{\partial x^\rho}, \frac{\partial}{\partial x^\tau}\right) \\
&= \frac{1}{2}\omega_{\mu\nu} X_1^{\rho} X_2^{\tau} \sum_{\sigma \in S_2}\mathrm{sgn}
\begin{pmatrix}
\mu & \nu \\
\sigma(\mu) & \sigma(\nu) \\ 
\end{pmatrix}
\delta^{\sigma(\mu)}_{\rho}
\delta^{\sigma(\nu)}_{\tau} \\
&= \frac{1}{2} \sum_{\sigma \in S_2}\mathrm{sgn}
\begin{pmatrix}
\mu & \nu \\
\sigma(\mu) & \sigma(\nu) \\ 
\end{pmatrix}
\omega_{\mu\nu} X_1^{\sigma(\mu)} X_2^{\sigma(\nu)} \\
\end{aligned}
++++

ここで latexmath:[\mu], latexmath:[\nu]は、はダミー添字であり、総和 latexmath:[\sum_{\mu,\nu}]は省略されている。したがって、同じ総和の中で添字を交換しても式の値は変わらず、項をまとめるための書き換えとして扱える。

[stem,latexmath]
++++
\begin{aligned}
&= \frac{1}{2} \sum_{\sigma \in S_2}\mathrm{sgn}
\begin{pmatrix}
\sigma(\mu) & \sigma(\nu) \\
\mu & \nu \\
\end{pmatrix}
\omega_{\sigma(\mu)\sigma(\nu)} X_1^{\mu} X_2^{\nu} \\
\end{aligned}
++++

latexmath:[\mathrm{sgn}(\sigma^{-1})=\mathrm{sgn}(\sigma)^{-1}=\mathrm{sgn}(\sigma)]であるから、

[stem,latexmath]
++++
\begin{aligned}
&= \frac{1}{2} \sum_{\sigma \in S_2}\mathrm{sgn}
\begin{pmatrix}
\mu & \nu \\
\sigma(\mu) & \sigma(\nu) \\
\end{pmatrix}
\omega_{\sigma(\mu)\sigma(\nu)} X_1^{\mu} X_2^{\nu} \\
\end{aligned}
++++

ここで完全反対称性より、 latexmath:[\omega_{\mu\nu} = \mathrm{sgn}(\sigma) \omega_{\sigma(\mu) \sigma(\nu)}]であるから:

[stem,latexmath]
++++
\begin{aligned}
&= \frac{1}{2} \sum_{\sigma \in S_2} \omega_{\mu\nu} X_1^{\mu} X_2^{\nu} \\
&= \frac{1}{2} \omega_{\mu\nu} X_1^{\mu} X_2^{\nu} \sum_{\sigma \in S_2} 1 \\
&= \frac{1}{2} \omega_{\mu\nu} X_1^{\mu} X_2^{\nu} |S_2| \\
&= \omega_{\mu\nu} X_1^{\mu} X_2^{\nu} \\
\end{aligned}
++++

以上より、

[stem,latexmath]
++++
\omega(X_1, X_2) = \omega_{\mu\nu} X_1^{\mu} X_2^{\nu}.
++++


====  3-形式の例(p53)

テンソル積の定義から 3-形式 は、latexmath:[\mu \lt \nu \lt \rho]として、latexmath:[dx^{\mu} \wedge dx^{\nu} \wedge dx^{\rho}]を基底とした latexmath:[{m \choose 3}]次元のベクトル空間を考え、次のように定義される。ここでは 3次元基底 latexmath:[x^1], latexmath:[x^2], latexmath:[x^3] を固定しているので、latexmath:[\mu], latexmath:[\nu], latexmath:[\rho] は 1, 2, 3 の値をとるラベルとして扱い、和の省略は明示的に「同じ添字が 2回現れるとき」のみ適用する。

[stem,latexmath]
++++
\begin{aligned}
dx^{\mu} \wedge dx^{\nu} \wedge dx^{\rho}
&=
dx^{\mu} \otimes dx^{\nu} \otimes dx^{\rho} + dx^{\nu} \otimes dx^{\rho} \otimes dx^{\mu} \\
&\quad + dx^{\rho} \otimes dx^{\mu} \otimes dx^{\nu} - dx^{\nu} \otimes dx^{\mu} \otimes dx^{\rho} \\
&\quad - dx^{\mu} \otimes dx^{\rho} \otimes dx^{\nu} - dx^{\rho} \otimes dx^{\nu} \otimes dx^{\mu} \\
&= \sum_{\sigma \in S_3}\mathrm{sgn}
\begin{pmatrix}
\mu & \nu & \rho \\
\sigma(\mu) & \sigma(\nu) & \sigma(\rho) \\ 
\end{pmatrix}
dx^{\sigma(\mu)} \otimes dx^{\sigma(\nu)} \otimes dx^{\sigma(\rho)}
\end{aligned}
++++


3-形式 latexmath:[\displaystyle \omega=\frac{1}{3!}\omega_{\mu\nu\rho} d x^\mu \wedge d x^\nu \wedge d x^\rho]と3つのベクトル場 latexmath:[\displaystyle X_i = X_i^\nu \frac{\partial}{\partial x^\nu}\, (i=1,2,3)]から、双対ペアリングを多重線形写像に拡張した関数を得られる。

[stem,latexmath]
++++
\begin{aligned}
\omega(X_1, X_2, X_3) 
&= \frac{1}{3!}\omega_{\mu_1\mu_2\mu_3} \; d x^{\mu_1} \wedge d x^{\mu_2} \wedge d x^{\mu_3} \left(X_1^{\nu_1} \frac{\partial}{\partial x^{\nu_1}}, X_2^{\nu_2} \frac{\partial}{\partial x^{\nu_2}}, X_3^{\nu_3} \frac{\partial}{\partial x^{\nu_3}} \right) \\
&= \frac{1}{3!}\omega_{\mu_1\mu_2\mu_3} X_1^{\nu_1} X_2^{\nu_2} X_3^{\nu_3} \; d x^{\mu_1} \wedge d x^{\mu_2} \wedge d x^{\mu_3} \left( \frac{\partial}{\partial x^{\nu_1}}, \frac{\partial}{\partial x^{\nu_2}}, \frac{\partial}{\partial x^{\nu_3}} \right) \\
\end{aligned}
++++

合わせてテンソル積の評価 latexmath:[(\alpha \otimes \beta \otimes \gamma)(X, Y, Z) = \alpha (X) \beta (Y) \gamma(Z)]であるから、次のようになる。

[stem,latexmath]
++++
\begin{aligned}
& dx^{\mu_1} \wedge dx^{\mu_2} \wedge dx^{\mu_3}
\, \left(
  \frac{\partial}{\partial x^{\nu_1}},
  \frac{\partial}{\partial x^{\nu_2}},
  \frac{\partial}{\partial x^{\nu_3}}
\right) \\
&= \sum_{\sigma \in S_3}\mathrm{sgn}
\begin{pmatrix}
\mu_1 & \mu_2 & \mu_3 \\
\sigma(\mu_1) & \sigma(\mu_2) & \sigma(\mu_3) \\ 
\end{pmatrix}
dx^{\sigma(\mu_1)} \otimes dx^{\sigma(\mu_2)} \otimes dx^{\sigma(\mu_3)}
\, \left(
  \frac{\partial}{\partial x^{\nu_1}},
  \frac{\partial}{\partial x^{\nu_2}},
  \frac{\partial}{\partial x^{\nu_3}}
\right) \\
&= \sum_{\sigma \in S_3}\mathrm{sgn}
\begin{pmatrix}
\mu_1 & \mu_2 & \mu_3 \\
\sigma(\mu_1) & \sigma(\mu_2) & \sigma(\mu_3) \\ 
\end{pmatrix}
dx^{\sigma(\mu_1)} \left(\frac{\partial}{\partial x^{\nu_1}}\right)
dx^{\sigma(\mu_2)} \left(\frac{\partial}{\partial x^{\nu_2}}\right)
dx^{\sigma(\mu_3)} \left(\frac{\partial}{\partial x^{\nu_3}}\right) \\
&= \sum_{\sigma \in S_3}\mathrm{sgn}
\begin{pmatrix}
\mu_1 & \mu_2 & \mu_3 \\
\sigma(\mu_1) & \sigma(\mu_2) & \sigma(\mu_3) \\ 
\end{pmatrix}
\delta^{\sigma(\mu_1)}_{\nu_1}
\delta^{\sigma(\mu_2)}_{\nu_2}
\delta^{\sigma(\mu_3)}_{\nu_3} \\
\end{aligned}
++++

ここまでを元の式に代入すると、次のようになる。

[stem,latexmath]
++++
\begin{aligned}
\omega(X_1, X_2, X_3) 
&= \frac{1}{3!}\omega_{\mu_1\mu_2\mu_3} \; d x^{\mu_1} \wedge d x^{\mu_2} \wedge d x^{\mu_3} \left(X_1^{\nu_1} \frac{\partial}{\partial x^{\nu_1}}, X_2^{\nu_2} \frac{\partial}{\partial x^{\nu_2}}, X_3^{\nu_3} \frac{\partial}{\partial x^{\nu_3}} \right) \\
&= \frac{1}{3!}\omega_{\mu_1\mu_2\mu_3} X_1^{\nu_1} X_2^{\nu_2} X_3^{\nu_3} \; d x^{\mu_1} \wedge d x^{\mu_2} \wedge d x^{\mu_3} \left( \frac{\partial}{\partial x^{\nu_1}}, \frac{\partial}{\partial x^{\nu_2}}, \frac{\partial}{\partial x^{\nu_3}} \right) \\
&= \frac{1}{3!}\omega_{\mu_1\mu_2\mu_3} X_1^{\nu_1} X_2^{\nu_2} X_3^{\nu_3} \;
\sum_{\sigma \in S_3}\mathrm{sgn}
\begin{pmatrix}
\mu_1 & \mu_2 & \mu_3 \\
\sigma(\mu_1) & \sigma(\mu_2) & \sigma(\mu_3) \\ 
\end{pmatrix}
\delta^{\sigma(\mu_1)}_{\nu_1}
\delta^{\sigma(\mu_2)}_{\nu_2}
\delta^{\sigma(\mu_3)}_{\nu_3} \\
&= \frac{1}{3!}
\sum_{\sigma \in S_3}\mathrm{sgn}
\begin{pmatrix}
\mu_1 & \mu_2 & \mu_3 \\
\sigma(\mu_1) & \sigma(\mu_2) & \sigma(\mu_3) \\ 
\end{pmatrix}
\omega_{\mu_1\mu_2\mu_3} X_1^{\sigma(\mu_1)} X_2^{\sigma(\mu_2)} X_3^{\sigma(\mu_3)} \\
&= \frac{1}{3!}\sum_{\sigma\in S_3}\mathrm{sgn}(\sigma)\,\omega_{\mu_1\mu_2\mu_3}\,X_1^{\sigma(\mu_1)}X_2^{\sigma(\mu_2)}X_3^{\sigma(\mu_3)} \\
\end{aligned}
++++

ここで、添字置換を行う(index relabelling latexmath:[\mu_i\mapsto\sigma(\mu_i)]):

[stem,latexmath]
++++
\begin{aligned}
&= \frac{1}{3!}\sum_{\sigma\in S_3}\mathrm{sgn}(\sigma^{-1})\omega_{\sigma(\mu_1)\sigma(\mu_2)\sigma(\mu_3)}\,X_1^{\mu_1}X_2^{\mu_2}X_3^{\mu_3} \\
\end{aligned}
++++

置換の偶奇は逆元を取っても変わらないので、 latexmath:[\mathrm{sgn}(\sigma^{-1})=\mathrm{sgn}(\sigma)] が成り立つ。実際、符号写像 latexmath:[\mathrm{sgn}: S_n \to \{\pm1\}]は準同型であり latexmath:[\mathrm{sgn}(\sigma^{-1})=\mathrm{sgn}(\sigma)^{-1}]である。また、latexmath:[\mathrm{sgn}(\sigma) \in \{\pm 1\}]であり、latexmath:[\{\pm 1\}]は乗法に関する二元群である。この群では、latexmath:[1 \cdot 1 = 1]、 latexmath:[(-1) \cdot (-1) = 1]であり、つまり任意の latexmath:[a \in \{-1, 1\}]に対して latexmath:[a \cdot a = 1]であり、 latexmath:[a^{-1} = a]が成り立つ。ここで latexmath:[a=\mathrm{sgn}(\sigma)]とすれば、 latexmath:[\mathrm{sgn}(\sigma)^{-1}=\mathrm{sgn}(\sigma)]となる。つまり、 latexmath:[\mathrm{sgn}(\sigma^{-1})=\mathrm{sgn}(\sigma)^{-1}=\mathrm{sgn}(\sigma)]である。

[stem,latexmath]
++++
\begin{aligned}
&= \frac{1}{3!}\sum_{\sigma\in S_3}\mathrm{sgn}(\sigma)\omega_{\sigma(\mu_1)\sigma(\mu_2)\sigma(\mu_3)}\,X_1^{\mu_1}X_2^{\mu_2}X_3^{\mu_3} \\
\end{aligned}
++++

ここで完全反対称性より、 latexmath:[\omega_{\mu_1 \mu_2 \mu_3} = \mathrm{sgn}(\sigma) \omega_{\sigma(\mu_1)\sigma(\mu_2)\sigma(\mu_3)}]であるから:

[stem,latexmath]
++++
\begin{aligned}
&= \frac{1}{3!}\sum_{\sigma\in S_3} \omega_{\mu_1 \mu_2 \mu_3} \,X_1^{\mu_1}X_2^{\mu_2}X_3^{\mu_3} \\
\end{aligned}
++++

\(\sigma\)の項が消えたので、\(S_3\)の和となる(latexmath:[|S_3|=3!]となることに注意する):

[stem,latexmath]
++++
\begin{aligned}
&= \frac{1}{3!}|S_3| \omega_{\mu_1 \mu_2 \mu_3} \,X_1^{\mu_1}X_2^{\mu_2}X_3^{\mu_3} \\
&= \omega_{\mu_1 \mu_2 \mu_3} \,X_1^{\mu_1}X_2^{\mu_2}X_3^{\mu_3} \\
\end{aligned}
++++

=== 問題2.12 (p54)
問:: 式(2.12)を示せ。

解答::
k-形式 latexmath:[\displaystyle \omega=\frac{1}{k!}\omega_{\mu_1 \cdots \mu_k} \, d x^{\mu_1} \wedge \cdots \wedge d x^{\mu_k}]に対して、 _k_ 個のベクトル場 latexmath:[\displaystyle X_i = X_i^\nu \frac{\partial}{\partial x^\nu}\, (i=1,2,\cdots,k)]から、双対ペアリングを多重線形写像に拡張した関数を得られる。
+
[stem,latexmath]
++++
\omega(X_1,\cdots,X_k)=\frac{1}{k!}\omega_{\mu_1 \cdots \mu_k} \; d x^{\mu_1} \wedge \cdots \wedge d x^{\mu_k} \left(X_1^{\nu_1}\frac{\partial}{\partial x^{\nu_1}}, \cdots, X_k^{\nu_k}\frac{\partial}{\partial x^{\nu_k}}\right)
++++
ここで、テンソル積の定義から _k_-形式は次のように定義できる。
+
[stem,latexmath]
++++
\begin{aligned}
dx^{\mu_1} \wedge \cdots \wedge dx^{\mu_3}
&:= \sum_{\sigma \in S_k}\mathrm{sgn}
\begin{pmatrix}
\mu_1 & \cdots & \mu_k \\
\sigma(\mu_1) & \cdots & \sigma(\mu_k) \\ 
\end{pmatrix}
dx^{\sigma(\mu_1)} \otimes \cdots \otimes dx^{\sigma(\mu_3)} \\
\end{aligned}
++++
合わせてテンソル積の評価 latexmath:[(\mu_1 \otimes \cdots \otimes \mu_k)(X_1, \cdots, X_k) = \mu_1 (X_1) \cdots \mu_k(X_k)]であるから、次のようになる。
+
[stem,latexmath]
++++
\begin{aligned}
& dx^{\mu_1} \wedge \cdots \wedge dx^{\mu_k}
\, \left(
  \frac{\partial}{\partial x^{\nu_1}},
  \cdots,
  \frac{\partial}{\partial x^{\nu_k}}
\right) \\
&= \sum_{\sigma \in S_k}\mathrm{sgn}
\begin{pmatrix}
\mu_1 & \cdots & \mu_k \\
\sigma(\mu_1) & \cdots & \sigma(\mu_k) \\ 
\end{pmatrix}
\,
dx^{\sigma(\mu_1)} \otimes \cdots \otimes dx^{\sigma(\mu_3)} \, \left(
  \frac{\partial}{\partial x^{\nu_1}},
  \cdots,
  \frac{\partial}{\partial x^{\nu_k}}
\right) \\
&= \sum_{\sigma \in S_k}\mathrm{sgn}
\begin{pmatrix}
\mu_1 & \cdots & \mu_k \\
\sigma(\mu_1) & \cdots & \sigma(\mu_k) \\ 
\end{pmatrix}
\,
dx^{\sigma(\mu_1)} \left(\frac{\partial}{\partial x^{\nu_1}}\right)
\cdots
dx^{\sigma(\mu_k)} \left(\frac{\partial}{\partial x^{\nu_k}}\right) \\
&= \sum_{\sigma \in S_k}\mathrm{sgn}
\begin{pmatrix}
\mu_1 & \cdots & \mu_k \\
\sigma(\mu_1) & \cdots & \sigma(\mu_k) \\ 
\end{pmatrix}
\, \delta_{\nu_1}^{\sigma(\mu_1)} \cdots \delta_{\nu_k}^{\sigma(\mu_k)}
\end{aligned}
++++
ここまでを元の式に代入すると、次のようになる。
+
[stem,latexmath]
++++
\begin{aligned}
\omega(X_1,\cdots,X_k)
&=\frac{1}{k!}\omega_{\mu_1 \cdots \mu_k} \; d x^{\mu_1} \wedge \cdots \wedge d x^{\mu_k} \left(X_1^{\nu_1}\frac{\partial}{\partial x^{\nu_1}}, \cdots, X_k^{\nu_k}\frac{\partial}{\partial x^{\nu_k}}\right) \\
&= \frac{1}{k!}\omega_{\mu_1 \cdots \mu_k} \; d x^{\mu_1} \wedge \cdots \wedge d x^{\mu_k} \left(X_1^{\nu_1} \frac{\partial}{\partial x^{\nu_1}}, \cdots, X_k^{\nu_k} \frac{\partial}{\partial x^{\nu_k}} \right) \\
&= \frac{1}{k!}\omega_{\mu_1 \cdots \mu_k} X_1^{\nu_1} \cdots X_k^{\nu_k} \; d x^{\mu_1} \wedge \cdots \wedge d x^{\mu_k} \left( \frac{\partial}{\partial x^{\nu_1}}, \cdots, \frac{\partial}{\partial x^{\nu_k}} \right) \\
&= \frac{1}{k!}\omega_{\mu_1 \cdots \mu_k} X_1^{\nu_1} \cdots X_k^{\nu_k} \;
\sum_{\sigma \in S_k}\mathrm{sgn}
\begin{pmatrix}
\mu_1 & \cdots & \mu_k \\
\sigma(\mu_1) & \cdots & \sigma(\mu_k) \\ 
\end{pmatrix}
\delta^{\sigma(\mu_1)}_{\nu_1} \cdots \delta^{\sigma(\mu_k)}_{\nu_k} \\
&= \frac{1}{k!}
\sum_{\sigma \in S_k}\mathrm{sgn}
\begin{pmatrix}
\mu_1 & \cdots & \mu_k \\
\sigma(\mu_1) & \cdots & \sigma(\mu_k) \\ 
\end{pmatrix}
\omega_{\mu_1 \cdots \mu_k} X_1^{\sigma(\mu_1)} \cdots X_k^{\sigma(\mu_k)} \\
&= \frac{1}{k!}\sum_{\sigma\in S_k}\mathrm{sgn}(\sigma)\,\omega_{\mu_1 \cdots \mu_k}\,X_1^{\sigma(\mu_1)} \cdots X_k^{\sigma(\mu_k)} \\
\end{aligned}
++++
ここで、添字置換を行う
+
[stem,latexmath]
++++
\begin{aligned}
&= \frac{1}{k!}\sum_{\sigma\in S_k}\mathrm{sgn}(\sigma^{-1})\omega_{\sigma(\mu_1)\cdots\sigma(\mu_k)}\,X_1^{\mu_1} \cdots X_k^{\mu_k} \\
\end{aligned}
++++
ここで完全反対称性を仮定すると、latexmath:[\omega_{\sigma(\mu_1) \cdots \sigma(\mu_k)} = \mathrm{sgn}(\sigma)\omega_{\mu_1 \cdots \mu_k}]であり、latexmath:[\mathrm{sgn}(\sigma^{-1}) = \mathrm{sgn}(\sigma)]から:
+
[stem,latexmath]
++++
\begin{aligned}
&= \frac{1}{k!}\sum_{\sigma\in S_k}\mathrm{sgn}(\sigma^{-1}) \, \mathrm{sgn}(\sigma) \, \omega_{\mu_1 \cdots \mu_k} \,X_1^{\mu_1} \cdots X_k^{\mu_k} \\
&= \frac{1}{k!}\sum_{\sigma\in S_k}\mathrm{sgn}(\sigma) \, \mathrm{sgn}(\sigma) \, \omega_{\mu_1 \cdots \mu_k} \,X_1^{\mu_1} \cdots X_k^{\mu_k} \\
&= \frac{1}{k!}\sum_{\sigma\in S_k} \omega_{\mu_1 \cdots \mu_k} \,X_1^{\mu_1} \cdots X_k^{\mu_k} \\
\end{aligned}
++++
\(\sigma\)の項が消えたので、\(S_k\)の和となる(latexmath:[|S_k|=k!]となることに注意する):
+
[stem,latexmath]
++++
\begin{aligned}
&= \frac{1}{k!}|S_k| \omega_{\mu_1 \cdots \mu_k} \,X_1^{\mu_1} \cdots X_k^{\mu_k} \\
&= \omega_{\mu_1 \cdots \mu_k} \,X_1^{\mu_1} \cdots X_k^{\mu_k} \\
\end{aligned}
++++
以上より、式(2.12)が示された。

=== 外微分の局所座標を用いない定義 (p56)

[stem,latexmath]
++++
\begin{align}
& (d\omega)(X_1,\cdots,X_{k+1}) \\
&\quad = \sum_{i=1}^{k+1}(-1)^{i+1} X_i(\omega(X_1,\cdots,\widehat{X_i}, \cdots, X_{k+1})) \\
&\quad\quad - \sum_{1 \le i \lt j \le k+1}(-1)^{i+j+1} \omega(\lbrack X_i, X_j \rbrack,\cdots,\widehat{X_i}, \cdots, \hat{X}_j, \cdots, X_{k+1}) \tag{2.13} \label{def_2_13}
\end{align}
++++

.記法の補足
* latexmath:[\widehat{X_i}]とあるのは、latexmath:[X_i]だけ除くことを意味している
* latexmath:[\lbrack X_i, X_j \rbrack]は、ベクトル場の交換子積で latexmath:[\lbrack X, Y \rbrack = XY - YX]と定義する

.1-形式の場合
====
latexmath:[X_i(\omega(X_2))]は、双対ペアリングで作られたスカラー関数 latexmath:[\omega(X_2)]に微分作用素としてのベクトル場 \(X_1\)が作用して得られたスカラー関数となる
[stem,latexmath]
++++
d\omega(X_1,X_2) = X_1(\omega(X_2)) - X_2(\omega(X_1)) - \omega(\lbrack X_1, X_2 \rbrack)
++++
====

=== 問題2.13 (p56)
問:: 座標を使った外微分の <<chap02_2_4.adoc#mjx-eqn-def_2_9,定義(2.9)>> が、上の座標を用いない外微分の定義式 latexmath:[\eqref{def_2_13}] を満たすことを示せ。
