ifndef::leveloffset[]
:toc: left
:toclevels: 3
:icons: font
:stem: latexmath
endif::[]

ifndef::imagesdir[]
:imagesdir: images
endif::[]

ifeval::["{backend}" == "html5"]
pass:[<script src="https://cdn.plot.ly/plotly-latest.min.js"></script>]
endif::[]

include::header.adoc[]

include::../../attrs.adoc[]

== 微分幾何入門 第一章

=== 問題1.6 (p8)
問:: 2次元球面(単位球面)
latexmath:[S^2 = \{(\cos \varphi \sin \theta, \sin \varphi \sin \theta, \cos \theta) \in \mathbb{R}^3 | 0 \leq \varphi \leq \pi, 0 \leq \theta \leq 2\pi\}]に対して、座標近傍 latexmath:[(U_i, \varphi_i)]を latexmath:[(\cos \varphi \sin \theta, \sin \varphi \sin \theta, \cos \theta) \mapsto (\varphi, \theta)]となるよう適当な開被覆で覆ってアトラスを構成せよ。また変換関数、 latexmath:[\Psi_{ij}も求めよ]

=== 問題1.7 (p12)
問:: _T_^2^ に適当なアトラスを定めよ

=== 問題1.8 (p13)
問:: 実射影空間の構成で、 latexmath;[x=ay]であるとき latexmath:[x \sim y]としたが、この関係が同値関係であること示せ。

=== 問題1.9 (p13)
問:: latexmath:[\mathbb{R}P^2]がどのような図形になるか考えよ

=== 問題1.10 (p14)
問::
多様体としての開区間I=(-pi/2, pi/2)とRが微分同相であることを示せ。 +
(I ⊂ R は開区間(a,b)であればなんでもよいことも簡単にわかる)

**回答**

latexmath:[f: I\to \mathbb{R}]の写像に対して、 latexmath:[f(\theta \in I) = \tan\theta]を考えると、__I__から__R__への微分同相写像であることがわかる。

=== 問題1.11 (p19)
問:: 多様体M上の曲線 _I_ → _M_ とそれを含む座標近傍 latexmath:[(U_i, \varphi_i)]、latexmath:[\varphi_i: U_i \to V_i \subset \mathbb{R}^m]を考える。 _M_ 上の関数 latexmath:[f: M \to \mathbb{R}]に対して、 latexmath:[\frac{df}{ft}]は座標の取り方によらないことを示せ。すなわち、曲線のパラメータを latexmath:[t \in I]とし、曲線上の点 _p_ の座標を latexmath:[\varphi_i(p(t)) = (x^1(t),\cdots,x^m(t))]としても、 latexmath:[\varphi_i^{\prime}(p(t)) = (y^1(t),\cdots,y^m(t))]としても、どちらで計算しても同じであることを示せ

=== 問題1.12 (p21)
問::
例1.8では、latexmath:[\boldsymbol{r}_{(1)}(t)]に沿った接ベクトルが latexmath:[\displaystyle\frac{d}{dt}=\frac{\partial}{\partial\varphi}]、latexmath:[\boldsymbol{r}_{(2)}(t)]に沿った接ベクトルが latexmath:[\displaystyle\frac{d}{dt}=\frac{\partial}{\partial\theta}]であることを確認せよ。

* 点 _p_ を通る緯線 latexmath:[\boldsymbol{r}_{(1)}(t) := (x^1(t), x^2(t), x^3(t)) = (\sin\theta_0 \cos t, \sin\theta_0 \sin t, \cos \theta_0)]
* 点 _p_ を通る経線 latexmath:[\boldsymbol{r}_{(2)}(t) := (x^1(t), x^2(t), x^3(t)) = (\sin t \cos\varphi_0, \sin t \sin\varphi_0, \cos t)]

*回答*

まず、latexmath:[\boldsymbol{r}_{(1)}(t)]、および latexmath:[\boldsymbol{r}_{(2)}(t)] に沿った接ベクトルを求める。

[stem,latexmath]
++++
\begin{aligned}
\frac{d\boldsymbol{r}_{(1)}}{dt}(t)
&= \left(\frac{dx^1(t)}{dt}, \frac{dx^2(t)}{dt}, \frac{dx^3(t)}{dt} \right) \\
&= \left(-\sin\theta_0\sin t, \sin\theta_0\cos t, 0 \right) \\
\end{aligned}
++++

[stem,latexmath]
++++
\begin{aligned}
\frac{d\boldsymbol{r}_{(2)}}{dt}(t)
&= \left(\frac{dx^1(t)}{dt}, \frac{dx^2(t)}{dt}, \frac{dx^3(t)}{dt} \right) \\
&= \left(\cos t \cos\varphi_0, \cos t \sin\varphi_0, -\sin t \right) \\
\end{aligned}
++++

続いて、 latexmath:[\boldsymbol{r}(\theta, \varphi)=(\sin\theta \cos\varphi, \sin\theta \sin\varphi, \cos\theta)]  偏微分を行う。

[stem,latexmath]
++++
\begin{aligned}
\frac{d\boldsymbol{r}(\theta, \varphi)}{dt}
&= \frac{d\theta}{dt}\frac{\partial\boldsymbol{r}}{\partial\theta} + \frac{d\varphi}{dt}\frac{\partial\boldsymbol{r}}{\partial\varphi} \\
&= \frac{d\theta}{dt}(\cos\theta \cos\varphi, \cos\theta \sin\varphi, -\sin\theta) + \frac{d\varphi}{dt}(-\sin\theta \sin\varphi, \sin\theta \cos\varphi, 0) \\
\end{aligned}
++++

この式から、最終的に、 latexmath:[\displaystyle\frac{d}{dt}=\frac{\partial}{\partial\varphi}]、latexmath:[\displaystyle\frac{d}{dt}=\frac{\partial}{\partial\theta}]であることがわかる。

=== 問題1.13 (p25)
問:: 同値関係と同値類の定義を思い出し、上の関係(p24-p25 定義1.4)が同値関係であることを確かめよ

=== 問題1.14 (p27)
latexmath:[M=\mathbb{R}]上で定義されたベクトル場 latexmath:[X=x\frac{\partial}{\partial y} - y\frac{\partial}{\partial x}]の様子を図示せよ。

ifeval::["{backend}" == "html5"]
**ベクトル場 X = x ∂/∂y - y ∂/∂x**
[pass]
++++
<div id="chap01_01_14_vector_field_plot_area"><!-- Plotly chart will be drawn inside this DIV --></div>
<script>
include::js/chap01_01_14_vector_field.js[]
</script>
++++
endif::[]

=== 問題1.15 (p31)
問:: 座標の取り方に依存しない双対ペアリングの概念が定まるには、双対な基底の間の関係が座標の取り方によらない必要がある。余接ベクトルXと接ベクトルYに対する双線形写像 latexmath:[<X,Y> \in \mathbb{R}]を考えたとき、
+
[stem,latexmath]
++++
\left\langle d x^{\mu}, \frac{\partial}{\partial x^{\nu}} \right\rangle = \delta_{\nu}^{\mu}
++++
+
という関係が座標変換で変化しないことを確かめよ。

**回答**

別の座標 _y_ において双対ペアリングを計算すると、双線形性から、次の結果が得られる。
[stem,latexmath]
++++
\begin{aligned}
\left\langle d y^{\mu}, \frac{\partial}{\partial y^{\nu}} \right\rangle 
&= \left\langle
  \frac{\partial y^{\mu}}{\partial x^{\tau}} d x^{\tau},
  \frac{\partial x^{\rho}}{\partial y^{\nu}} \frac{\partial}{\partial x^\rho}
\right\rangle
 = \frac{\partial y^{\mu}}{\partial x^{\tau}} \frac{\partial x^{\rho}}{\partial y^{\nu}} \left\langle d x^{\tau}, \frac{\partial}{\partial x^\rho} \right\rangle \\
&= \frac{\partial y^{\mu}}{\partial x^{\tau}} \frac{\partial x^{\rho}}{\partial y^{\nu}} \delta_{\rho}^{\tau} \\
&= \frac{\partial y^{\mu}}{\partial x^{\tau}} \frac{\partial x^{\tau}}{\partial y^{\nu}} \\
&= \delta_{\nu}^{\mu}
\end{aligned}
++++

=== 問題1.16 (p33)
問:: latexmath:[\mathbb{R}^2]のある点 _p_ での接空間 latexmath:[T_p \mathbb{R}^2]の基底を latexmath:[\displaystyle\frac{\partial}{\partial x},\frac{\partial}{\partial y}]とし、余接空間 latexmath:[T_p^{*} \mathbb{R}^2]の基底を _dx_, _dy_ とするとき、それらを使い latexmath:[T_p \mathbb{R}^2 \otimes T_p^{*} \mathbb{R}^2]の基底を示せ。