ifndef::leveloffset[]
:toc: left
:toclevels: 3
:icons: font
endif::[]

include::header.adoc[]

:stem: latexmath
include::../attrs.adoc[]

== Differential geometry

=== Constructing an atlas
An atlas is a collection of charts that provide local coordinate systems. A chart is a map that supplies a local coordinate system. An atlas plays an important role in understanding the structure of surfaces and manifolds.

==== Example: Atlas of the unit circle S^1^ (the real 1-dimensional projective line)

A point (x, y) on the unit circle S^1^ can be expressed as:
[stem,latexmath]
++++
S^1 = \left\{(x, y) \mid x^2 + y^2 = 1 \right\}
++++

To cover the circle S^1^ above, we can consider the following two charts:
[stem,latexmath]
++++
\begin{aligned}
U_1 &=  S^1\setminus\left\{(0, 1)\right\}
 \\
U_2 &=  S^1\setminus\left\{(0, -1)\right\} \\
\end{aligned}
++++

Both are open sets on the circle, and obviously _U_~1~ {cup} _U_~2~ = _S_^1^.

These charts provide local coordinate systems as follows.

Chart 1: _U_~1~: a map from S^1^ with the north pole (0, 1) removed

[stem,latexmath]
++++
\phi_1: U_1 \to \mathbb{R}, \quad \phi_1 (x, y) \mapsto \frac{x}{1-y}
++++

Chart 2: _U_~2~: a map from S^1^ with the south pole (0, -1) removed

[stem,latexmath]
++++
\phi_2: U_2 \to \mathbb{R}, \quad \phi_2 (x, y) \mapsto \frac{x}{1+y}
++++

Transition function (transition map between charts)

[stem,latexmath]
++++
\phi_2 \circ \phi_1^{-1}: \phi_1(U_1 \cap U_2) \to \phi_2(U_1 \cap U_2)
++++

重なり _U_~1~ ∩ _U_~2~ 上で次の s,t を計算する。 +
Calculate the following s and t on the overlapping region _U_~1~ ∩ _U_~2~.

[stem,latexmath]
++++
t=\phi_1(x, y), \quad s = \phi_2(x, y)
++++

次の式から、最終的に _s_ を消去して latexmath:[x(t), y(t)] を求める。 +
From the following equations, eliminate _s_ and find latexmath:[x(t), y(t)].
// Equation 1
[stem,latexmath]
++++
\begin{equation}
t(x,y) = \frac{x}{1-y} \tag{1}\label{tag_t_xy}
\end{equation}
++++

// Equation 2
[stem,latexmath]
++++
\begin{equation}
s(x,y) = \frac{x}{1+y} \tag{2}\label{tag_s_xy}
\end{equation}
++++

// Equation 3
[stem,latexmath]
++++
\begin{equation}
x^2 + y^2 = 1 \tag{3}\label{tag_x2_y2_1}
\end{equation}
++++

latexmath:[\eqref{tag_t_xy}] と latexmath:[\eqref{tag_s_xy}] から、 _x_ を消去して、次のように式を整理できる。 +
From latexmath:[\eqref{tag_t_xy}] and latexmath:[\eqref{tag_s_xy}], eliminate _x_ and rearrange the equation as follows.

[stem,latexmath]
++++
\begin{aligned}
t(1 - y) = x,\quad& s(1 + y)=x \\
t(1 - y) &= s(1 + y) \\
t - ty &= s + sy \\
(s + t)y &= t - s \\
y &= \frac{t - s}{t + s} \\
\end{aligned}
++++

latexmath:[\eqref{tag_t_xy}] と latexmath:[\eqref{tag_s_xy}] から、 _y_ を消去して、次のように式を整理できる。 +
From latexmath:[\eqref{tag_t_xy}] and latexmath:[\eqref{tag_s_xy}], eliminate _y_ and rearrange the equation as follows.
[stem,latexmath]
++++
\begin{aligned}
t(1 - y) = x,\quad& s(1 + y)=x \\
t - ty = x,\quad& s + sy = x \\
t - x = ty,\quad& sy = x - s \\ 
st - sx = sty,\quad& sty = tx - st \\
st - sx &= tx - st \\
(s + t)x &= 2st \\
x &= \frac{2st}{s + t} \\
\end{aligned}
++++

_x_^2^ + _y_^2^ = 1 latexmath:[\eqref{tag_x2_y2_1}] から、_s_, _t_ の関係を導き出す。
[stem,latexmath]
++++
\begin{aligned}
x^2 + y^2 &= 1, s\ne 0, t\ne 0 \\
\left(\frac{2st}{s + t}\right)^2 + \left(\frac{t - s}{t + s}\right)^2 &= 1, s\ne 0, t\ne 0 \\
4s^2t^2 + (t - s)^2 &= (t + s)^2, s\ne 0, t\ne 0 \\
0 &= (t + s)^2 - (t - s)^2 - 4s^2t^2, s\ne 0, t\ne 0 \\
0 &= (t + s + t - s)(t + s - t + s) - 4s^2t^2, s\ne 0, t\ne 0 \\
0 &= 2t \cdot 2s - 4s^2t^2, s\ne 0, t\ne 0 \\
0 &= st(1 - st), s\ne 0, t\ne 0 \\
st &= 1 \\
\end{aligned}
++++

_x_(_s_,_t_) と _y_(_s_,_t_) から _s_ を消去して、次のように式を整理できる。 +
From _x_(_s_,_t_) and _y_(_s_,_t_), eliminate _s_ and rearrange the equation as follows.

[stem,latexmath]
++++
\begin{aligned}
x &= \frac{2st}{s + t} = \frac{2}{\frac{1}{t} + t} = \frac{2t}{t^2 + 1} \\
y &= \frac{t - s}{t + s} = \frac{t - \frac{1}{t}}{t + \frac{1}{t}} = \frac{t^2 - 1}{t^2 + 1} \\
\end{aligned}
++++

逆写像を使って次のように表すことができる。 +
Using the inverse map, it can be expressed as follows.
[stem,latexmath]
++++
\begin{aligned}
x &= \frac{2t}{t^2 + 1} \\
y &= \frac{t^2 - 1}{t^2 + 1}
\end{aligned}
++++

変換関数(transition map)は次のように表すことができる。 +
The transition function can be expressed as follows.
[stem,latexmath]
++++
\begin{aligned}
\phi_2(x(t), y(t)) \circ \phi_1^{-1}(t)
&= \left. \frac{x(t)}{1 + y(t)} \right|_{x(t)=\frac{2t}{t^2 + 1}, y(t)=\frac{t^2 - 1}{t^2 + 1}} \\
&= \frac{\frac{2t}{t^2 + 1}}{1 + \frac{t^2 - 1}{t^2 + 1}} \\
&= \frac{2t}{t^2 +1 + t^2 - 1} \\
&= \frac{2t}{2t^2} \\
&= \frac{1}{t} \\
\end{aligned}
++++

連続性の確認 +
Check the continuity.

遷移写像は latexmath:[t \ne 0]上で無限回微分可能であるため、連続である。 +
The transition map is infinitely differentiable on latexmath:[t \ne 0], so it is continuous.

したがって (_U_~1~, _phi_~1~) と (_U_~2~, _phi_~2~) は S^1^ の C^∞^ アトラスを構成する。 +
Thus, (_U_~1~, _phi_~1~) and (_U_~2~, _phi_~2~) form an atlas of S^1^.

==== Example: Atlas of the unit sphere S^2^ (stereographic projection) 

The unit sphere S^2^ can be expressed as:
[stem,latexmath]
++++
x^2 + y^2 + z^2 = 1
++++

To cover the sphere S^2^, we can consider the following two charts:
[stem,latexmath]
++++
\begin{aligned}
U_N &=  S^2\setminus\left\{(0, 0, -1)\right\}
 \\
U_S &=  S^2\setminus\left\{(0, 0, 1)\right\} \\
\end{aligned}
++++

座標関数（ステレオ投影） +
Coordinate functions (stereographic projection)

Chart N: _U_~N~: projection from the north pole
[stem,latexmath]
++++
\begin{aligned}
\phi_N(x, y, z): U_N \to \mathbb{R}^2, \quad \phi_N (x, y, z) \mapsto \left(\frac{x}{1 + z}, \frac{y}{1 + z}\right) = (u_N, v_N)
\end{aligned}
++++

Chart S: _U_~S~: projection from the south pole
[stem,latexmath]
++++
\begin{aligned}
\phi_S(x, y, z): U_S \to \mathbb{R}^2, \quad \phi_S (x, y, z) \mapsto \left(\frac{x}{1 - z}, \frac{y}{1 - z}\right) = (u_S, v_S)
\end{aligned}
++++

変換関数 +
Transition function

重なり _U_~N~ ∩ _U_~S~ 上で次の u~N~, u~S~ を計算する。 +
Calculate the following u~N~, u~S~ on the overlapping region _U_~N~ ∩ _U_~S~.

次の式から、最終的に _u_~S~, _v_~S~ を消去して x(_u_~N~),y(_u_~N~),z(_u_~N~)を求める。 +
From the following equations, eliminate _u_~S~, _v_~S~ and find x(_u_~N~),y(_u_~N~),z(_u_~N~).

[stem,latexmath]
++++
\begin{equation}
(u_N, v_N) = \left(\frac{x}{1 + z}, \frac{y}{1 + z} \right) \tag{1}\label{tag_R3_north_map_uv}
\end{equation}
++++

[stem,latexmath]
++++
\begin{equation}
(u_S, v_S) = \left(\frac{x}{1 - z}, \frac{y}{1 - z} \right) \tag{2}\label{tag_R3_south_map_uv}
\end{equation}
++++

[stem,latexmath]
++++
\begin{equation}
x^2 + y^2 + z^2 = 1 \tag{3}\label{tag_x2_y2_z2_1}
\end{equation}
++++

latexmath:[\eqref{tag_R3_north_map_uv}] と _x_^2^ + _y_^2^ + _z_^2^ = 1 latexmath:[\eqref{tag_x2_y2_z2_1}] から、_u_~N~, _v_~N~ の関係を導き出す。 +
From latexmath:[\eqref{tag_R3_north_map_uv}] and _x_^2^ + _y_^2^ + _z_^2^ = 1 latexmath:[\eqref{tag_x2_y2_z2_1}], derive the relationship between _u_~N~ and _v_~N~.
[stem,latexmath]
++++
\begin{aligned}
x^2 + y^2 + z^2 &= 1, & z \ne \pm 1 \\
\left\{u_N (1 + z)\right\}^2 + \left\{v_N (1 + z)\right\}^2 + z^2 &= 1, & z \ne \pm 1 \\
\left\{u_N (1 + z)\right\}^2 + \left\{v_N (1 + z)\right\}^2 &= 1 - z^2, & z \ne \pm 1 \\
u_N^2 + v_N^2 &= \frac{1 - z^2}{(1 + z)^2}, & z \ne \pm 1 \\
u_N^2 + v_N^2 &= \frac{1 - z}{1 + z}, & z \ne \pm 1 \\
\end{aligned}
++++

あとで、この結果を用いる。 +
We will use this result later.

[stem,latexmath]
++++
\begin{equation}
u_N^2 + v_N^2 = \frac{1 - z}{1 + z} \tag{6}\label{tag_R3_norm_of_phi_n}
\end{equation}
++++

球面上の点 _p_(_x_, _y_, _z_)について、 latexmath:[\phi_N(x, y, z) = (u_N, v_N)]のとき、 
逆写像は latexmath:[\eqref{tag_R3_north_map_uv}]より、次のように表すことができる。 +
For a point _p_(_x_, _y_, _z_) on the sphere, when latexmath:[\phi_N(x, y, z) = (u_N, v_N)], the inverse map can be expressed as follows from latexmath:[\eqref{tag_R3_north_map_uv}].

[stem,latexmath]
++++
\begin{aligned}
\phi_N^{-1}(u_N, v_N) &\to (x, y, z) \\
\phi_N^{-1}(u_N, v_N) &= \left(u_N (1 + z), v_N (1 + z), z \right) \\
\end{aligned}
++++

latexmath:[\eqref{tag_R3_south_map_uv}] から、
latexmath:[\phi_S(x, y, z) = \left(\frac{x}{1 - z},\frac{y}{1 - z}\right)]となるから、変換関数は次のように整理することができる。 +
From latexmath:[\eqref{tag_R3_south_map_uv}], since latexmath:[\phi_S(x, y, z) = \left(\frac{x}{1 - z},\frac{y}{1 - z}\right)], the transition function can be rearranged as follows.

[stem,latexmath]
++++
\begin{aligned}
\left(\phi_S (x, y, z) \circ \phi_N^{-1}\right)(u_N, v_N)
&= \phi_S (\phi_N^{-1}(u_N, v_N)) \\
&= \phi_S (u_N (1 + z), v_N (1 + z), z) \\
&= \left.
  \left( \frac{x}{1 - z}, \frac{x}{1 - z} \right)
\right|_{(u_N (1 + z), v_N (1 + z), z)} \\
&= \left( \frac{u_N (1 + z)}{1 - z}, \frac{v_N (1 + z)}{1 - z} \right) \\
&= \frac{1 + z}{1 - z}(u_N, v_N) \\
\end{aligned}
++++

さらに、latexmath:[\eqref{tag_R3_norm_of_phi_n}] から、最終的に次のような形になる。 +
Furthermore, from latexmath:[\eqref{tag_R3_norm_of_phi_n}], it can be expressed in the following form.
[stem,latexmath]
++++
\begin{aligned}
\left(\phi_S (x, y, z) \circ \phi_N^{-1}\right)(u_N, v_N)
&= \frac{1 + z}{1 - z}(u_N, v_N) \\
&= \left(\frac{u_N}{u_N^2 + v_N^2}, \frac{v_N}{u_N^2 + v_N^2}\right) \\
\end{aligned}
++++

変換関数は、 latexmath:[(u_N, v_N) \ne (0, 0)]上で滑らかとなる。 +
The transition function is smooth on latexmath:[(u_N, v_N) \ne (0, 0)].

==== Example: Real projective line RP^1^
To cover the real projective line RP^1^, we can consider the following two charts:
[stem,latexmath]
++++
\begin{aligned}
U_1 &=  RP^1\setminus\left\{[0:1]\right\} = \left\{[x:y] \mid y \ne 0\right\} \\
U_2 &=  RP^1\setminus\left\{[1:0]\right\} = \left\{[x:y] \mid x \ne 0\right\} \\
\end{aligned}
++++

座標関数 +
Coordinate functions
Chart 1: _U_~1~: a map from RP^1^ with the point [0:1] removed
[stem,latexmath]
++++
\begin{aligned}
\phi_1: U_1 \to \mathbb{R}, \quad \phi_1 ([x:y]) \mapsto \frac{x}{y}
\end{aligned}
++++

Chart 2: _U_~2~: a map from RP^1^ with the point [1:0] removed
[stem,latexmath]
++++
\begin{aligned}
\phi_2: U_2 \to \mathbb{R}, \quad \phi_2 ([x:y]) \mapsto \frac{y}{x}
\end{aligned}
++++

逆写像は次のように表すことができる。 +
The inverse map can be expressed as follows.
[stem,latexmath]
++++
\begin{aligned}
\phi_1^{-1}: \mathbb{R} \to U_1, \quad \phi_1^{-1}(t) = [t:1]
\end{aligned}
++++

変換関数 +
Transition function
[stem,latexmath]
++++
\begin{aligned}
\phi_2 \circ \phi_1^{-1}: \phi_1(U_1 \cap U_2) \to \phi_2(U_1 \cap U_2)
\end{aligned}
++++

重なり _U_~1~ ∩ _U_~2~ 上で次の t を計算する。 +
Calculate the following t on the overlapping region _U_~1~ ∩ _U_~2~.
[stem,latexmath]
++++
\begin{aligned}
t = \phi_1([x:y])
\end{aligned}
++++
次の式から、最終的に _t_ を消去して latexmath:[\lbrack x:y \rbrack] を求める。 +
From the following equations, eliminate _t_ and find latexmath:[\lbrack x:y \rbrack].
[stem,latexmath]
++++
\begin{aligned}
t &= \frac{x}{y} \\
\phi_1^{-1}(t) &= [t:1] \\
\phi_2 \circ \phi_1^{-1}(t) &= \phi_2([t:1]) = \frac{1}{t} \\
\end{aligned}
++++

連続性の確認 +
Check the continuity.
遷移写像は latexmath:[t \ne 0]上で無限回微分可能であるため、連続である。 +
The transition map is infinitely differentiable on latexmath:[t \ne 0], so it is continuous.
したがって (_U_~1~, _phi_~1~) と (_U_~2~, _phi_~2~) は RP^1^ の C^∞^ アトラスを構成する。 +
Thus, (_U_~1~, _phi_~1~) and (_U_~2~, _phi_~2~) form an atlas of RP^1^.
